---
title: "Flowering 6CV"
author: "CT"
date: "06.07.2017"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r loadLibraries, warning=FALSE}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)

```
This script calculates the means of DAS and TTAS50Flo for Iversen to join the Reanalysis table 

```{r loadFile}

setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\FlowIv2")

getwd()

#create file
df_f <- read.table("df_tt_50p_flow.txt",header=TRUE)

head (df_f)
```
check formats
```{r}
str(df_f)

```
Here only graph by month of sowing for report 

```{r}

a <-df_f %>%
  mutate(SowingD=ymd(SowingD))
  str(a)

  a%>%
    #use filter to check single variables -Bud, Flowering and Bur
  filter( Cultivar == "Monti") %>%
  filter(Variable=="Flowering"| Variable == "Bur")%>%
  tidyr::gather("Variable3","Value",DAS50F:TT50F) %>%
  mutate(Variable3=as.factor(Variable3))%>%
  ggplot(aes(x=SowingD,y=Value,colour=Cultivar, shape=Cultivar))+
    #scale_x_discrete(name="Mon")
  geom_point()+
  geom_line(aes(colour=Variable))+
  facet_grid(Variable3~., scales="free")+
  theme_bw()+
 # theme(axis.text.x = element_text(angle = 0, hjust = 1.5))+
  #scale_x_date(date_breaks = "1 month",date_labels =  "%b")+
labs(x="Sowing Month")+
    #limits = as.Date (c("2016"))
ylab(expression(Tt~"("^"o"*"Cd)"~~~~~~~~~~~~~~~~~~~~~~Days))
    


  
```

```{r}
write.table(a, "graph.txt")
```



Analysis of sowing date and cultivars for Bud considering Date 

```{r GraphBoxPlotBud}

 df_50Iv <- df_f %>%
  group_by(Cultivar,SowTreat,Variable)%>%
  filter (Variable=="Flowering"| Variable== "Bur")%>%
  summarise_each(funs(mean))

str(df_50Iv)

```

```{r}



df_50Iv %>%
  #use filter to check single variables -Bud, Flowering and Bur
  filter( Cultivar == "Monti") %>%
  tidyr::gather("Variable3","Value",DAS50F:TT50F) %>%
  mutate(Variable3=as.factor(Variable3))%>%
  ggplot(aes(x=SowTreat,y=Value,colour=Variable3, shape=Variable3))+
  geom_point()+
  geom_line()+
  facet_grid(Variable3~., scales="free")+
  theme_bw()+
 # theme(axis.text.x = element_text(angle = 0, hjust = 1.5))+
  #scale_x_date(date_breaks = "1 month",date_labels =  "%b")+
labs(x="SowTreat")+
ylab(expression(Tt~"("^"o"*"Cd)"~~~~~~~~~~~~~~~~~~~~~~1/Days))
```



Save df as a table to join with Reanalysis table  

```{r GraphSowingDateAndVariable,fig.width=10}

write.table(df_50Iv, "df_50Iv.txt")


```

Now do the same for Poukawa in another script within Folder is FlowPok


