---
title: "Pp target for S1"
author: "CT"
date: "Thursday, December  05, 2016"
output:
  word_document: default
  pdf_document: default
  html_document: default
note: include Pp analysis using selected datasets from Reanalysis4 (df_REa6)
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library (segmented)
library(hydroGOF)

```
 


```{r   loadFile}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\FlowIv2")

getwd()

#get dataframe created similar to ReAnalysis4 which is Rea6 - use Iversen DAS50Flwoering data
df_t <- read.table("S1_50Flo.txt",header=TRUE)

str(df_t)

```







Create function for retrieving photoperiod as a function of TT after sowing


```{r}

df_CumTT <- read.table("df_CumTTIv.txt",header=TRUE)

summary (df_CumTT)

```


```{r}
df_CumTT2 <- df_CumTT %>%
  select(LocationYear, Date, SumTTday,Pp)%>%
  mutate()

  summary (df_CumTT2)
  str(df_CumTT2)
  
```


```{r}
# force date format
df_t$SowingDate <- dmy(df_t$SowingDate)
df_t$StartFlowering <- dmy(df_t$StartFlowering)
str(df_t)

```


```{r}
# get TTsum at sowing
df_Iv <- merge(df_t, df_CumTT2,
               by.x=c("LocationYear","SowingDate"), 
               by.y=c("LocationYear","Date"))

df_Iv$TTSumSow <- df_Iv$SumTTday

head(df_Iv)

str(df_Iv)
```


```{r}

# Select parameters 
df_weather <- df_CumTT2 %>%
dplyr::select(LocationYear,Date, Pp, SumTTday)

summary(df_weather)



```



```{r}


Pp_finder_func <- function(idx_loc,tt_target){
  
  #isolate the experiment and cultivar 
  df_temp_wea <- df_weather %>%
    filter(LocationYear == idx_loc)
  
 # tt_target <- tt_sow + tt_extra
  
  # lookup for Pp at new tt sum
  tryCatch(  
  Pp_target <- approx(df_temp_wea$SumTTday, 
  df_temp_wea$Pp, xout = tt_target, rule = 1)$y,
  error = function(e) 
  {
  Pp_target <- NA
  }
)
 
  return(Pp_target)
  
}
```

```{r}
#test
tt_target <- 100.00
#TTsum estimated to reach 1st trifoliate 

#test if function is working : example : 
Pp_finder_func("Iversen2_2015",tt_target)
```

Create the loop to identify each combination of indexLocCult - isolate and calculate stats for each Pp target. 

```{r}

#FIXME: use RMSE instrad of R2 to find best fit

#Flowering reference = flowRefPerc
flowRefPerc <- 50

TTpercflo <- 2.6 # degree days from 5 to full (100) flowering 
#value calculated from DearEtAL1993_Reanalysis3 script

# find max value of TTjuv possible per crop group
 ttJuvMax <- df_Iv %>%
   filter(Variable=="TTtoFlower") %>%
   group_by(Treatcultivar) %>%
  summarise(ttJuvMax = min(Value))

#loop
cvGroup <- unique(df_Iv$Treatcultivar)
vc_temp <- vector()
vc_all <- vector()

#i=t=1

for(i in 1:length(cvGroup)){
  
  for(t in seq(0,max(ttJuvMax$ttJuvMax), by=100)){
    
   if(t > ttJuvMax$ttJuvMax[ttJuvMax$Treatcultivar==cvGroup[i]]) break # do not allow TTjuv > min of TT to flower
   
   #print(t)
  #print(i)
 
  cvG <- cvGroup[i]
  
  #print(s) 
  
  df_s <- df_Iv %>%
    #dplyr::filter(Treatcultivar == cvG) %>% no need to include this filter here...need to seed for all cultivars 
    
    filter(Variable=="TTtoFlower") %>%
    mutate(ttFlowZero = Value - (flowRefPerc*TTpercflo)) %>% 
    mutate(z = TTSumSow + t) %>% #define multiple tt after sowing for which Pp needs to be retrieved 
    mutate(TT_target= ifelse (z > ttFlowZero,
                             ttFlowZero,
                             z)) %>%
    #mutate(z=TTSumSow + t) %>% #testing Pp even if Pp greater than experienced by crop
    rowwise() %>%
    #mutate(Pp_target=Pp_finder_func(TT_target)) # functions gets a charater therefore format changes
     mutate(Pp_target=Pp_finder_func(as.character(LocationYear),TT_target)) # functions gets a charater therefore format change
    #print(unique(df_s$indexLocCult))
    
    x <- as.numeric(df_s$Pp_target)
    y <- as.numeric(df_s$Value)
  
  # test alternative functions - all gave highest first R2 at ~ 600oCd - Not resolved
 #  polyM <- lm(formula = y ~ poly(x, 3)) # testing simple polinomial
 #  expM <- lm(log(y)~ x)
 #  print(t)
 #  print( summary(polyM)$r.squared*100)
 #  summary(polyM)
  # -------
  
  out.lm <-lm(Value~Pp_target,data=df_s)
  
    # way to get eq coeff  
  summary(out.lm) 
  intT <- out.lm$coefficients[1]
  slopeT<- out.lm$coefficients[2]
  # Here need to change value of Pp_target for each sowing date?? 
  
    # o <- segmented(out.lm,seg.Z=~Pp_target,psi=list(Pp_target=13),
    #                control=seg.control(display=FALSE))
  o <- segmented(out.lm,seg.Z=~Pp_target,psi=list(Pp_target=11),
                   control=seg.control(display=FALSE))
  
  # test plot FIXME: Does not display what we expected?
  print(t)
  plot(x,y, pch=16)
  plot(o, add=T, link=TRUE)
  
      
  
  # find stats
      s <- slope(o)$Pp[,1]    
      interc <- intercept(o)
    
    #  r2 <- round(summary.segmented(o)$adj.r.squared*100,digits=5)
      r2 <- round(summary.segmented(o)$r.squared*100,digits=5)
      slope1 <- round(s[1], digits = 4)
      slope2 <- round(s[2], digits = 4)
      pVs1 <- summary.segmented(o)$coefficients[14]#pvalue slope1
      pVs2 <-summary.segmented(o)$coefficients[15]#pvalue slope2
      
      # find breaks
      b = o$psi[,2]
      
      vc_temp <- c(as.character(cvG),t, r2,slope1,slope2,pVs1,pVs2,b)
      vc_all <- rbind(vc_all,vc_temp)
      # show slopes and breakpoints
      #print(paste0(" slope: ",s, " break: ", b))
      
     # print(summary(o))
  
}  #this ends the loop of multiple thermal time
vc_temp <-NULL
 } #end loop high and low  cultivars
  
 #Here need to include sowing date
 df_all <-data.frame(vc_all)
 colnames(df_all) <-c("CvGroup","TTjuv", "r2","slope1","slope2","pVs1","pVs2","b")
 
 # FIXME: The resulting model does not align with the best "visual" fit at 900oCd Tt juveline
 

```

```{r, fig.height=3}
#graph it 

df_all %>%
   ggplot(aes(x=as.numeric(as.character(TTjuv)), 
              y=as.numeric(as.character(r2)), colour=CvGroup)) +
  labs(x="Thermal Time  (oCd)", y="R2")+
  theme_bw()+
   geom_point() +
  geom_line()
```

```{r}
# summary(df_Rea7)
# #need to write a table for script 8 - vernalization
# write.table(df_Rea7, "df_Rea8.txt")
```


```{r , warning = FALSE}

# find highest r2

#graph PPat 1000TTjuv 
df_opt <- df_all %>%
group_by(CvGroup) %>%
filter(r2==max(as.numeric(as.character(r2))))

#tt_extra_opt <- 700

ggg <- c("Late","Early")

# for(gg in 1:length(ggg)) {
# for(tte in 1:length(tt_extra_opt)) {
  
   dt1 <- df_Rea7 %>%
     rowwise() %>%
    #dplyr::filter(SensGroup == ggg[gg]) %>%
    filter(Variable == "TTFloAdj") %>%
     mutate(tt_extra_opt=as.numeric(ifelse(SensGroup=="Late",900,700)))%>%
     mutate(TT_target = TTSumSow + tt_extra_opt) %>% #define multiple thermal time after sowing for which photoperiod needs to be retrieved 
    
    mutate(Pp_target = Pp_finder_func(as.character(LocationYear),TT_target)) %>%
    mutate(tt_juv_toflower=Value-tt_extra_opt)
   
  # how to get quadratic coefficients? FIXME 
  # library(broom) 
  # dt1 %>%
  #    group_by(SensGroup) %>%
  #    do(fitTT = tidy(lm(Pp_target ~ Value +Value^2, data = .)))
  # 
 
  
   
   
  g <- dt1 %>%
    ggplot(aes(x=Pp_target,y=Value)) +
     #ggplot(aes(x=Pp_target,y=tt_juv_toflower)) + #test Pp versus the TTdiferential form Juvenile to flower
    geom_point(aes(shape=factor(SeasonYear),colour=reorder(Month, month(SowingDate)))) +
    # stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1) + 
     stat_smooth(method = "lm", formula = y ~ poly(x, 2), size = 1)+
     geom_abline(intercept = ifelse(df_Rea7$SensGroup=="Late",900,700), slope=0,linetype=2)+
     geom_vline(xintercept = 14, linetype=2)+
     labs(x="Photoperiod at inductive phase (hours)", y="Thermal Time to flower (degree days)")+
     facet_wrap(~SensGroup)+
     theme(legend.position="top") +
    labs(shape="Season", colour="Sowing Month")

   
   print(g)
  
# }
# 
# }

# loop acros multiple TT extras
# select best stats or simply store all (better I think) and test in next chunck
   

```

```{r}
# get empirical coefficients of equation
  polyType <- 2 # two as we'll do quadratic

polFit_df <- dt1 %>%
  group_by(SensGroup) %>%
  do(fittedEq = lm(Value ~ poly(Pp_target,polyType,raw = TRUE), data = .)) # note that raw is TRUE not to get orthogonal coeff
# loop through results and get coefficients

# get size of loop
noFactors <- length(unique(dt1$SensGroup)) # how many factors?
noCoeff <-   polyType + 1 # how many coeficients (plynomial no + 1 intercept)

# loop and print each coeff
for (f in 1:noFactors) {
  
  print("-----------------------------------------")
  print(dt1$SensGroup[f])
  
  
  for (c in 1:noCoeff) {
    
    print(paste0("Coeff_",c,": ",unname(polFit_df$fittedEq[[f]]$coefficients[c]) ))# remove coeff names
  }
  print(paste0("R2: ",(summary(polFit_df$fittedEq[[f]])$r.squared))) 
  print(paste0("R2 adjusted: ",(summary(polFit_df$fittedEq[[f]])$adj.r.squared)))
}
```


Now bring data vernalization from Reanalysis 8


```{r}

#from Vernalization calc
df_temp <- read.table("df_tempVern.txt",header=TRUE)

df_tempVern <- df_temp %>%
  mutate(SowingDate = ymd(as.Date(SowingDate)))

summary(df_tempVern)

str(df_tempVern)


```

```{r}
#merge with df_Rea6

df_Rea7$SowingDate <- ymd(as.Date(df_Rea7$SowingDate))
df_tempVern$SowingDate <- ymd(as.Date(df_tempVern$SowingDate))


df_ReaVerna <- merge(df_Rea7, df_tempVern, by=c("AuthorYear","Location","Treatcultivar","SowingDate"))

str(df_ReaVerna)



```

```{r}
summary(df_ReaVerna)
```

Here select the optimum TT at Pptarget find the inctive phase based on best curve fit  

```{r, fig.height=5, fig.width= 10}

# find highrest r2

#graph PPat 1000TTjuv 
df_opt <- df_all %>%
group_by(CvGroup) %>%
filter(r2==max(as.numeric(as.character(r2))))

#tt_extra_opt <- 700

ggg <- c("Late","Early")

# for(gg in 1:length(ggg)) {
# for(tte in 1:length(tt_extra_opt)) {
  
   h <- df_ReaVerna %>%
     rowwise() %>%
    #dplyr::filter(SensGroup == ggg[gg]) %>%
    filter(Variable == "TTFloAdj") %>%
     #use this mutate(tt_extra_opt=as.numeric(ifelse(SensGroup=="Late",900,700)))%>%
     mutate(tt_extra_opt=as.numeric(ifelse(SensGroup=="Late",900,700)))%>%
     mutate(TT_target = TTSumSow + tt_extra_opt) %>% #define multiple thermal time after sowing for which photoperiod needs to be retrieved 
    mutate(Pp_target = Pp_finder_func(as.character(LocationYear),TT_target)) %>%
    mutate(tt_juv_toflower=Value-tt_extra_opt)
    
     
  


```

Graph it best fit 

```{r,fig.height=5, fig.width= 10}
h %>%
  #use this filter tofind PpInductive in each location
  #filter(Location== "Melbourne")%>%
     ggplot(aes(x=Pp_target,y=Value)) +
     #ggplot(aes(x=Pp_target,y=tt_juv_toflower)) + #test Pp versus the TTdiferential form Juvenile to flower
     geom_point(aes(shape=factor(SeasonYear), 
                    size=as.numeric(VerntoFlower),
                    colour=reorder(Month, month(SowingDate))
                  )) +
       scale_shape(solid = FALSE)+
    # stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1) + 
     stat_smooth(method = "lm", formula = y ~ poly(x, 2), size = 1)+
     geom_abline(intercept = ifelse(df_Rea7$SensGroup=="Late",900,700), slope=0,linetype=2)+
     geom_vline(xintercept = 14, linetype=2)+
     labs(x="Photoperiod at inductive phase", y ="Thermal Time to flower (degree days)")+
      theme(legend.position="top") +
       theme(text = element_text(size = 14))+
    labs(shape="Season", colour="Sowing Month", size = "Vernalisation Days")+
     facet_grid(.~SensGroup)

   print(h)
```



