---
title: "Spectrum Suberin Test versus suberin "
author: "CT"
date: "21 March 2017"
output: html_document
---

```{r setup, include=FALSE, loadlibraires}
#knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(scales)

```

compare the mean suberin spectra with the mean of all subclovers 

```{r readData}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\Spectra_S2_Anovas")
getwd()

#create file
#df_sp <- read.table("suberinbaselined.txt",header=TRUE)
df_sp <- read.table("Spectra_SuberinANDCuticle.txt",header=TRUE)

#head(df_sp)

str(df_sp)
```

## Graph it 



```{r}
df_sp <- df_sp %>%
mutate(wavelength = as.numeric(Wavenumber),
    AbsorbanceNorm =  as.numeric(AbsorbanceNorm))
    
```

Graph it but subset to make the same scale as per the seed coat spectrum 
```{r, fig.height=5, fig.width=10}

df_sp %>%
  #subset (wavelength<3800 & wavelength>650)%>%
  ggplot(aes(x=wavelength,y=AbsorbanceNorm))+
  geom_line(aes(colour=Material))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_y_continuous(breaks = seq(0, 1, by = 0.2))+
  scale_x_continuous(breaks = seq(650, 3950, by = 100))+
  scale_x_reverse(breaks = seq(650, 3950, by = 100))+
  #expand_limits(y=c(0,0.2)) +
  xlab(expression(Wavenumber~"(cm"^"-1"*")"))
  geom_abline(intercept = 0.1, slope = 0)


```

format 


```{r, fig.height=5, fig.width=20}

str(df_sp)

#adjust format and follow the same original script 
df_spSegment2<-df_sp  %>%
 # mutate(Days= as.factor(IncubationDays))%>%
  mutate (SpectraPart= factor(SpectraPart, levels=c("3600-2800", "1800-850")))%>%
  mutate (Material= factor(Material, levels=c("WoodCork","Cuticle"),labels=c("Wood","Cuticle")))%>%
  mutate (SpectraPart_f = factor(SpectraPart, levels=c('3600-2800','1800-850')))
 
 str(df_spSegment2)
                       
  
```

```{r, fig.height=10, fig.width=20}

df_spSegment2  %>%   
    #force spectra order here                              
     # df_spSegment$SpectraPart_f = factor(df_spSegment$SpectraPart, levels=c('3700-2700','1800-850'))%>% 
  ggplot(aes(x=Wavenumber,y=AbsorbanceNorm))+
    #geom_line(aes(), colour=IncubationDays))+
  #geom_line(aes(colour=Material),size=2)+
  geom_line(aes(linetype=Material), size=2)+
    scale_color_manual(values=c("black", "blue"))+
  theme_bw()+
  #scale_x_continuous(breaks=seq(min(df_sp$WaveNumber),max(df_sp$WaveNumber),by =50))+
    #scale_x_continuous(breaks=round(seq(min(df_sp$WaveNumber),max(df_sp$WaveNumber),by =50)))+
  #facet_grid(Cultivar_f ~SpectraPart_f,scales="free") +
  facet_grid(.~SpectraPart_f,scales="free") +
  #facet_grid(Cultivar ~.) +
  scale_x_reverse()+
  #scale_x_continuous(breaks=round(seq(min(df_sp$WaveNumber),max(df_sp$WaveNumber),by =50)))+
  
  theme_bw(base_size=30)+
  theme(strip.text.x =  element_blank())+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  expand_limits(y=c(0,1.2)) +
    labs(y= " Absorbance (au) ")+
    xlab(expression(Wavenumber~"(cm"^"-1"*")"))+
#theme(axis.text.y = element_text( size = 24))+
  #theme(axis.title.y = element_text(face="bold", size=14))+
#theme(axis.text.x=element_text(angle = 0, hjust=0.95,vjust=0.2,size = 28)) +
    
    #remove grid lines 
    
    #remove grid lines 
   theme(
     panel.border = element_rect(colour = "white", size = 2), 
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank(),

axis.line = element_line(colour = "black"))+
     #make cultivars white  
   theme(strip.background = element_rect(colour = "black", fill = "white",size=2))+
    #increase font size panels
    #theme(strip.text.x = element_text(size = 30, colour = "orange", angle = 90))+
    
theme(text = element_text(size = 32))+
theme(axis.text.y = element_text( size = 32))+
    theme(axis.title.y = element_text(face="bold", size=32))+
     scale_y_continuous(breaks = c(seq(from = 0, to = 1.25, by = 0.5)))+
theme(axis.text.x=element_text(angle = 0, hjust=0.5,vjust=0,size = 28))+
theme(axis.title.x = element_text( size=32,face="bold"))+
  theme(axis.line.x = element_line(colour = 'black', size = 3))+
  theme(axis.line.y = element_line(colour = 'black', size = 3))
  #axis line 
  #y.line = element_line(colour = 'black', size = 4)



   #Save graph 
 
 ggsave("plot_spectraComparSuberinCuticle.tiff", width=20, height=10, dpi=400)






```


#