---
title: "Spectra of S2All FTIR test"
author: "CT"
date: "17.09.2017"
output: html_document
#here files have already been baselined corrected in OPUS. Raw data is on folder Bionami Maatrix 25.04; worksheet Columns to R. In this script the analysis of wavenumber ranges and ANOVAS.
---


```{r setup, include=FALSE, loadlibraires}
#knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(scales)
#library(hyperSpec)

```


```{r readData}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\Spectra_S2_Anovas")
getwd()

info <- read.table ("S2All.txt",  header = TRUE)
##or launch the baselinedNormalised 


summary (info)

```
```{r}
str(info)
```


Adjust formats 

```{r}

info_av <- info %>%
  mutate(Plot=factor(Plot), Block=factor(Block), wavelength=factor(wavelength)) %>%
    dplyr::select(-Seed) %>%
  group_by(Plot, Cultivar,Block,wavelength) %>%
  summarise_all(funs(mean)) %>%
  mutate(wavelength=as.numeric(as.character(wavelength))) 

summary(info_av)

write.table(info_av, "Absorb_Per_WL.txt")

```

##Then transform spectra in Normalised spectra (used Mas. normalisation treatment on spectra )

##Keep columns names like that prior loop (easy) 


```{r}
info_av_norm <- info_av %>%
  mutate(AbsorbanceNorm=Absorbance/max(Absorbance)) %>%
  dplyr::select(-Hardness) %>%
  ungroup()
 
str(info_av_norm)

```
```{r}
summary(info_av_norm)
```



Loop throup spectra

Loop unique wavenumber 

Compare cultivars within each wavelength

```{r}

info_av_norm$id<- paste0(info_av_norm$wavelength)
idList <- unique(info_av_norm$id) 
length(idList)

print(paste0("Found ",length(idList)," wavelength by cultivar combinations to loop"))

data.all <- data.frame()

x <- 0 # for t test

for (i in 1:length(idList)) {
  
    #df <- df_sp2 %>%
  df <- info_av_norm %>%
    ungroup() %>%
    mutate(Plot=factor(Plot),Cultivar=factor(Cultivar), Block=factor(Block)) %>%
    subset(id == idList[i])
  
  #my.anova <- aov(AbsValue ~ IncubationDays + Rep, data = df)
  my.anova <- aov(AbsorbanceNorm ~ Cultivar + Block, data = df)
    
   
  pVals <- summary(my.anova)[[1]][["Pr(>F)"]]
 
    # T test when P<0.05
  if(!is.nan(pVals[1]) & pVals[1] < 0.05) {
  
  x <- x + 1
  t_test <-  LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none")
  lsd <- t_test$statistics[6] # getting  lsd
  
  this.data <- data.frame(WaveNumber = df$wavelength[1], PV = pVals[1], LSD = lsd, Count=x)
  
  data.all <- rbind(data.all, this.data)
  
  this.data <- NULL
  
  } else {
    
# do nothing
   
  }
  
}



```
```{r}
summary(data.all)
```


##---------------------till here is all good!
```{r}


#EMPTY
```

```{r}
#summary(data.all)


```

```{r, warning=FALSE}
data.all %>%
  ggplot(aes(x=WL,y=PV)) +
  geom_rect(data=NULL,aes(xmin=650,xmax=4000,ymin=0,ymax=0.05),fill="lightpink", alpha = 0.01) +
  geom_line() +
  theme_bw()+
  geom_abline(slope=0, intercept=0.05, linetype=2)+
   scale_x_reverse(breaks = seq(650, 4000, by = 100))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab(expression(Wavenumber~"(cm"^"-1"*")"))+
  ylab(expression(P~value ~"(P)"))
```

## Write data frame 

- as table for subsequent analysis 

```{r}

#write table in file 
write.table(data.all, "WavePvalues.txt")
getwd()
```

Then continue analysis in script 2 

