---
title: "Spectra of S2 FTIR test"
author: "CT"
date: "17.09.2017"
output: 
  word_document: default
  pdf_document: default
  html_document: default
#This script reads the Wavenumber and P values from previous script and get only the values that are significant (P < 0.05)   
---


```{r setup, include=FALSE, loadlibraires}
#knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(scales)
library(hyperSpec)

```


```{r readData}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover\\Spectra_S2_Anovas")
getwd()
file <- read.table ("WaveHardPvalues.txt",  header = TRUE)


str (file)

```
Adjust formats 

```{r}

# file1 <-file %>%
# mutate(
#     Plot = as.factor(Plot),
#     #wavelength = leave as integer for greaphics 
#     Block = as.factor(Block),
#     Cultivar = as.factor(Cultivar),
#     Hardness = as.numeric (Hardness),
#     Seed = as.factor(Seed)
#   )  
# 
# str (file1)


```
Subset a range of interest: P values below 0.05 


```{r}

df_0.05<-file %>%
  #subset range 3500-3200
  subset (PV>0 & PV<0.05)

```

## Graph it all data 

```{r, fig.height=4, fig.width=10}

df_0.05 %>%
  
  ggplot(aes(x=WL,y=PV))+
  geom_line(aes())+
  theme_bw()+
  scale_x_continuous(breaks = seq(650, 4000, by = 50))+
  #scale_x_continuous(breaks = seq(1150, 1200, by = 50))+
  #scale_x_reverse()+
  #scale_x_continuous(lim=c(650,4000))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  expand_limits(y=c(0,0.05)) +
  #expand_limits(x=650, 4000)+
  geom_abline(intercept = 0.02, slope = 0)


```

Get less data : try below 0.01 



```{r}
df_0.01<-file %>%
  #subset range 3500-3200
  subset (PV>0 & PV<0.01)

  
  


```

