---
title: "Spectra of S2All FTIR test"
author: "CT"
date: "18.09.2017"
output: 
  word_document: default
  pdf_document: default
  html_document: default
#here files have already been baselined corrected in OPUS. Raw data is on folder Bionami Maatrix 25.04 (CO2 to R); worksheet Columns to R. In this script the analysis of hardness and significant wavenumbers 
---


```{r setup, include=FALSE, loadlibraires}
#knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(scales)
library(hyperSpec)

```


```{r readData}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover\\Spectra_S2_Anovas")
getwd()
file <- read.table ("S2All.txt",  header = TRUE)

summary (file)

```
Adjust formats . Here hardness as factor for the loop 

```{r}

file1 <- file %>%
mutate(
    Plot = as.factor(Plot),
    #wavelength = leave as integer for greaphics 
    Block = as.factor(Block),
    Cultivar = as.factor(Cultivar),
    Hardness = as.factor(Hardness),
    Seed = as.factor(Seed),
    wavelength=as.factor(wavelength)
  )  %>%
  group_by(Hardness, Block, Plot,wavelength) %>%
  summarise(Absorbance=mean(Absorbance)) %>%
  mutate(wavelength=as.numeric(as.character(wavelength)))

summary (file1)


```
Graph colur by hardness and check

```{r}
file1 %>%
  dplyr::select(Hardness,Absorbance, wavelength)%>%
  group_by(Hardness,wavelength)%>%
  summarise_each(funs(mean))%>%
  #filter(Cultivar=="Monti"|Cultivar=="Woogenellup")%>%
  ggplot(aes(x=wavelength,y=Absorbance, colour=Hardness))+
           geom_line()+
  theme_bw()+
 #scale_x_continuous(breaks=seq(min(file1$wavelength),max(file1$wavelength),100))+
  #scale_x_reverse()+
  scale_y_continuous(breaks = seq(0, 0.16, by = 0.02))+
  scale_x_continuous(breaks = seq(650, 4000, by = 100))+
  scale_x_reverse(breaks = seq(650, 4000, by = 100))+
  #scale_x_continuous(lim=c(650,4000))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  #expand_limits(y=c(0,0.14)) +
  scale_y_continuous(breaks = seq(0, 0.14, by = 0.02))+
 xlab(expression(Wavenumber~"(cm"^"-1"*")"))
  #expand_limits(x=650, 4000)+
  #geom_abline(intercept = 0.1, slope = 0)


```



Loop throup spectra to compare hardness 


```{r}
# set limits
mn<-min(file1$wavelength)
mx<-max(file1$wavelength)
wv<- unique(file1$wavelength)


##print(paste0("Loop from ",mn," to ", mx))

data.all <- data.frame()

x <- 0 # for t test

#select the inteval of the spectra to analyse 
for(i in seq(from=1, to=length(wv), by=1)) {
  
  #print(wv[i])
  #print(paste0("Wavelength ",wv[i]))
  
  df <- file1 %>%
  subset(wavelength == wv[i])
  
  my.anova <- aov(Absorbance ~ Hardness + Block, data = df)
  
#  print(summary(my.anova))
  
  pVals <- summary(my.anova)[[1]][["Pr(>F)"]]
  
  
  # T test when P<0.05
  if(!is.nan(pVals[1]) & pVals[1] < 0.05) {
  
  x <- x + 1
  t_test <-  LSD.test(my.anova, c("Hardness"), alpha= 0.05, p.adj="none")
  #lsd <- t_test$statistics[4]
  
 # treats <- t(ttest$groups)[1,] # FIXME: in the case we need more info
 # mSep <- t(ttest$groups)[3,]

  } else {
    
   lsd <- NA
   
  }
  
  this.data = data.frame(WL = wv[i], PV = pVals[1], LSD = lsd)
  
  data.all <- rbind(data.all, this.data)
  
}

x

```

```{r}
summary(data.all)
```

```{r, warning=FALSE}
data.all %>%
  ggplot(aes(x=WL,y=PV)) +
  geom_rect(data=NULL,aes(xmin=650,xmax=4000,ymin=0,ymax=0.05),fill="lightpink", alpha = 0.01) +
  geom_line() +
  theme_bw()+
  geom_abline(slope=0, intercept=0.05, linetype=2)+
  #scale_x_reverse(breaks = seq(650, 4000, by = 100))+
  scale_x_reverse(breaks = seq(650, 4000, by = 100))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab(expression(Wavenumber~"(cm"^"-1"*")"))+
  ylab(expression(P~value ~"(P)"))
```

## Write data frame 

- as table for subsequent analysis 

```{r}

#write table in file 
write.table(data.all, "WaveHardPvalues.txt")
getwd()
```

Then continue analysis in script 2 

