---
title: "Flowering 6CV"
author: "CT"
date: "Thursday, December 31, 2015"
output: html_document
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)

```



```{r loadFile}
setwd("C:\\Users\\Ed\\Documents\\Subclovergit")
getwd()

#create file
df_flower <- read.table("F_Flower_SB_PhenologyData.txt",header=TRUE)
colnames(df_flower)[1] <- "Date" # fix bug of extra characters in name
# convert to date format
df_flower <- df_flower %>%
mutate(Date=dmy(Date))
str(df_flower)

  


```

Analysis of sowing date and cultivars for Bud considering Date 

```{rGraphBoxPlotBud}

 # df_flower$Date <- dmy(df_flower$Date) 
head(df_flower)
 df_flower %>%
  group_by(DAS,Date, Cultivar,SowTreat,Variable)%>%
  summarise_each(funs(mean)) %>%
  select(Variable,Percent, Cultivar,Date,SowTreat)%>%
  filter(Variable == "Bud") %>%
  
  ggplot(aes(x=Date, y=Percent)) + 
  #geom_bar(shape=1, stat="identity")
  geom_line(aes(colour=Cultivar)) +
  facet_grid(SowTreat~Cultivar, scales = "free")+
  geom_abline(intercept = 50, slope = 0)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
  #scale_x_continuous(breaks=c(2,3,4,5,6,7,8,9,10,11), labels=c("Fe","Mr","Ap","Ma","Ju","Jul","Au","Se","Oc","No"))
```


Analysis of Sowing dates and variables (from bud to bur4) considering DAS 

```{r GraphSowingDateAndVariable}
df_flower %>%
  mutate(Variable = 
  factor(Variable,levels = c("Bud","Early","Open",
          "Petal","Bur1","Bur2","Bur3","Bur4" ))) %>%
  group_by(DAS,Cultivar,SowTreat,Variable) %>%
  summarise_each(funs(mean)) %>%
  select(Variable,Percent, Cultivar,DAS,SowTreat) %>%
  filter(Cultivar == "Leura" | Cultivar =="Monti") %>%
  ggplot(aes(x=DAS, y=Percent)) + 
  #geom_bar(shape=1, stat="identity")
  geom_line(aes(colour=Cultivar)) +
  facet_grid(SowTreat~Variable, scales = "free") +
  geom_abline(intercept = 50, slope = 0)+
theme(axis.text.x = element_text(angle = 90, hjust = 1))



```

Join Thermal Sum data.


```{r join ThermalSum data}


#create file
df_TTSum <- read.table("ThermalSum.txt",header=TRUE)
#df_TTSum$Date <- ymd(df_TTSum$Date)

df_TTSum 
head(df_TTSum)
summary(df_TTSum  )
names(df_TTSum)
str(df_TTSum$Date)
tail(df_TTSum)
tail(df_flower)

# convert to date format
df_TTSum <- df_TTSum %>%
 mutate(Date=ymd(Date))

```

Merge two df : TTSum and Flowering 
```{r MergeTTSumDate}

 #merge two data frames by ID
df_flower <- merge(df_flower,df_TTSum,by="Date")
head(df_flower)
summary(df_flower )

#tidy up dataframe

names(df_flower)[1] <- "DateMeasure"
names(df_flower)[15] <- "TTMeasure"
```



```{r mergeTTSowDate,include=FALSE}

df_TTSow <-read.table("TTSowDate.txt", header=TRUE)
df_TTSow$MeanAirT<-NULL
names(df_TTSow)[3]
df_flower <- merge(df_flower,df_TTSow, by="SowTreat" )
head(df_flower)

#tidy up names
names(df_flower)[17] <- "TTSow"

```


```{r Calc_TT_afterSow}

df_flower$TTAS <- df_flower$TTMeasure-df_flower$TTSow

df_flower %>%
  mutate(Variable = 
  factor(Variable,levels = c("Bud","Early","Open",
          "Petal","Bur1","Bur2","Bur3","Bur4" ))) %>%
  group_by(TTAS,Cultivar,SowTreat,Variable) %>%
  summarise_each(funs(mean)) %>%
  select(Variable,Percent, Cultivar,TTAS,SowTreat) %>%
  #filter(Cultivar == "Monti") %>%
  filter(Variable == "Bud") %>%
  ggplot(aes(x=TTAS, y=Percent)) + 
  geom_line(aes(colour=Cultivar)) +
  facet_grid(SowTreat~Cultivar, scales = "free") +
  geom_abline(intercept = 50, slope = 0)+
theme(axis.text.x = element_text(angle = 60, hjust = 1))


#by variable 
df_flower %>%
  mutate(Variable = 
  factor(Variable,levels = c("Bud","Early","Open",
          "Petal","Bur1","Bur2","Bur3","Bur4" ))) %>%
  group_by(TTAS,Cultivar,SowTreat,Variable) %>%
  summarise_each(funs(mean)) %>%
  select(Variable,Percent, Cultivar,TTAS,SowTreat) %>%
  filter(Cultivar == "Monti" | Cultivar == "Leura" ) %>%
  #filter(Variable == "Bud") %>%
  ggplot(aes(x=TTAS, y=Percent)) + 
  geom_line(aes(colour=Cultivar)) +
  facet_grid(SowTreat~Variable, scales = "free") +
  geom_abline(intercept = 50, slope = 0)+
theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

Interpolate 50 Percent of a Variable Bud , cultivar and sowtreat.

```{r proxie50}
df_flower50 <- df_flower %>%
  group_by(Cultivar,SowTreat,Variable, DateMeasure) %>%
  summarise(avP= mean(Percent),avTT= mean(TTAS))

 w <- df_flower50 %>%
  filter(Variable=="Bud", Cultivar=="Leura",SowTreat=="S1" )

#interpolate 
tutu <- approx(w$avP,w$avTT , xout = 50)
tutu



# create loop to calculate all
cv <- unique(df_flower50$Cultivar)
var <- unique(df_flower50$Variable)
sow <- unique(df_flower50$SowTreat)

for(i in 1:length(cv)) {
  for(j in 1:length(var)){
    for(k in 1:length(sow)){
      
      print(paste0(cv[i],var[j], sow[k]))
      # filter for each combination
      
    }
    
  }
  
}




```




next step: join early_open and petal categories to create " flower" 

```{r joinEarlyOpenFlower}

# create df with flowering only (merged)
df_flower_simple <- df_flower %>%
filter(Variable == "Early" | Variable == "Open" | Variable == "Petal") %>%
group_by(DateMeasure, Plot) %>%
  mutate(Variable = "Flowering", 
         S1=max(S1), 
         S2=max(S2),
         S3=max(S3), 
         S4=max(S4),
         S5=max(S5),
         Percent=((S1+S2+S3+S4+S5)/5)*100)

# merge both dfs
df_flower_simple <- rbind(df_flower,df_flower_simple)

# graph it
df_flower_simple %>%
  filter(Variable == "Bud" |
           Variable =="Flowering"| 
           Variable =="Bur1"| 
           Variable =="Bur2"| 
           Variable =="Bur3"| 
           Variable =="Bur4")  %>%
  mutate(Variable = 
  factor(Variable,levels = c("Bud","Flowering",
                             "Bur1", "Bur2", "Bur3","Bur4"))) %>%
  group_by(TTAS,Cultivar,SowTreat,Variable) %>%
  summarise_each(funs(mean)) %>%
  select(Variable,Percent, Cultivar,TTAS,SowTreat) %>%
  filter(Cultivar == "Monti" | Cultivar == "Leura" ) %>%
  #filter(Variable == "Bud") %>%
  ggplot(aes(x=TTAS, y=Percent)) + 
  geom_line(aes(colour=Cultivar)) +
  facet_grid(SowTreat~Variable, scales = "free") +
  geom_abline(intercept = 50, slope = 0)+
theme(axis.text.x = element_text(angle = 60, hjust = 1))

unique(df_flower_simple$Variable)





```


```{r}

# create df with bur only (merged bur1,2,3 and 4)
df_bur_simple <- df_flower %>%
filter(Variable == "Bur1" | Variable == "Bur2" | Variable == "Bur3"| Variable == "Bur4" ) %>%
group_by(DateMeasure, Plot) %>%
  mutate(Variable = "Bur", 
         S1=max(S1), 
         S2=max(S2),
         S3=max(S3), 
         S4=max(S4),
         S5=max(S5),
         Percent=((S1+S2+S3+S4+S5)/5)*100)

# merge both dfs
df_bur_simple <- rbind(df_flower,df_flower_simple, df_bur_simple)

# graph it
df_bur_simple %>%
  filter(Variable == "Bud" |
           Variable =="Flowering"| 
           Variable =="Bur")  %>%
  mutate(Variable = 
  factor(Variable,levels = c("Bud","Flowering",
                             "Bur"))) %>%
  group_by(TTAS,Cultivar,SowTreat,Variable) %>%
  summarise_each(funs(mean)) %>%
  select(Variable,Percent, Cultivar,TTAS,SowTreat) %>%
  #filter(Cultivar == "Monti" | Cultivar == "Leura" ) %>%
  #filter(Variable == "Bud") %>%
  ggplot(aes(x=TTAS, y=Percent)) + 
  geom_line(aes(colour=Cultivar)) +
  geom_point(aes(shape=Cultivar,colour=Cultivar))+
  facet_grid(SowTreat~Variable, scales = "free") +
  geom_abline(intercept = 50, slope = 0)+
theme(axis.text.x = element_text(angle = 60, hjust = 1))

unique(df_bur_simple$Variable)
```



