---
title: "CreateMergedPhenologyStages"
author: "CT"
date: "Sunday, January 17, 2016"
output: html_document
---


```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)

```


```{r loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover")
getwd()

#create file
df_flower <- read.table("df_flower.txt",header=TRUE)
head(df_flower)
tail(df_flower)

summary(df_flower)

df_flower %>%
  filter(S1>1)


```


Merge phenological stages into "bud, flower and burr"

```{r joinEarlyOpenFlower}

# create df with flowering stages only (merged)
df_flower_simple <- df_flower %>%
filter(Variable == "Early" | 
         Variable == "Open" | 
         Variable == "Petal") %>%
group_by(Date, Plot) %>%
  mutate(Variable = "Flowering", 
         S1=max(S1), 
         S2=max(S2),
         S3=max(S3), 
         S4=max(S4),
         S5=max(S5),
         Percent=((S1+S2+S3+S4+S5)/5)*100)

# merge both dfs
#df_flower_simple <- rbind(df_flower, df_flower_simple)

# check
df_flower_simple %>%
  filter(Variable=="Flowering")  %>%
  head()


```

Do the same joining for Burr

```{r joinBurrStages}

# create df with bur only (merged bur1,2,3 and 4)
df_bur_simple <- df_flower %>%
filter(Variable == "Bur1" | 
         Variable == "Bur2" | 
         Variable == "Bur3"| 
         Variable == "Bur4" ) %>%
group_by(Date, Plot) %>%
  mutate(Variable = "Bur", 
         S1=max(S1), 
         S2=max(S2),
         S3=max(S3), 
         S4=max(S4),
         S5=max(S5),
         Percent=((S1+S2+S3+S4+S5)/5)*100)

# df with bud only
df_bud_simple <- df_flower %>%
  filter(Variable == "Bud")

# merge both dfs
df_bud_flow_bur_simple <- 
  rbind(df_bud_simple, df_flower_simple, df_bur_simple)

#check
summary(df_bud_flow_bur_simple)

# graph it
df_bud_flow_bur_simple %>%
  filter(Variable == "Bud" |
           Variable =="Flowering"| 
           Variable =="Bur")  %>%
  mutate(Variable = 
  factor(Variable,levels = c("Bud","Flowering",
                             "Bur"))) %>%
  group_by(DAS,Cultivar,SowTreat,Variable) %>%
  summarise_each(funs(mean)) %>%
  select(Variable,Percent, Cultivar,DAS,SowTreat, TTAS) %>%
  #filter(SowTreat == "S1" | SowTreat == "S2" ) %>%
  #filter(Cultivar == "Monti" | Cultivar == "Leura") %>%
  filter(Variable == "Flowering")%>%
 # ggplot(aes(x=DAS, y=Percent)) + 
  ggplot(aes(x=TTAS, y=Percent)) + 
  geom_line(aes(colour=Cultivar)) +
  geom_point(aes(shape=Cultivar,colour=Cultivar))+
  #facet_grid(Cultivar~SowTreat, scales = "free") +
  facet_grid(SowTreat~Cultivar, scales = "free") +
  geom_abline(intercept = 50, slope = 0) +
  ylab("Percent of Flowering (%)") +
  xlab("Thermal-time from sowing (oCd)")+
theme(axis.text.x = element_text(angle = 60, hjust = 1))


write.table(df_bud_flow_bur_simple, "df_bud_flow_bur_simple.txt")


```

