---
title: "Germination Seeds different Temperatures  4CV"
author: "CT"
date: " September  , 2015"
output: html_document
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)  
library(agricolae)
library(knitr)
library (lubridate)

```


```{r loadFile}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\SeedGermTemp")
getwd()

#create file
df_seed <- read.table("SeedGerm.txt",header=TRUE)
head(df_seed)
# Jeito 1 de trocar formato (usando base R)
df_seed$Date <- dmy(df_seed$Date)

# jeito 2 de trocar formato (usando dplyr)
df_seed <- df_seed %>%
  mutate(Temp = as.factor(Temp), rep = as.factor(rep))%>%
#  mutate(PropSoft =round((Soft/SeedNumber)*100),2)
  mutate(PropGerm = round(CountedGerm/50*100,digits=2))

summary(df_seed) # explore values
str(df_seed) # check formats
# head(df_seed) # see to rows
# tail(df_seed)

```



```{r, fig.width=14, fig.height= 5}
#graph it
 df_seed %>%
  group_by(Temp,Cv,rep) %>% # need to keep level in which cumulation occurs
  #arrange(HoursofTest) %>% # need to tell which factor to accumulate within
  arrange(DOT) %>%
  mutate(PropGerm_cum = cumsum(CountedGerm)) %>%
  #mutate(PropGermCum=PropGerm_cum/max(CountedGerm))%>%
  #group_by(Temp,Cv,HoursofTest) %>%
  group_by(Temp,Cv,DOT)%>%
  dplyr::select(Temp,Cv,DOT,PropGerm_cum) %>%
  summarise_all(funs(mean)) %>%
ggplot(aes(x=DOT, y=(PropGerm_cum/50)*100, colour=factor(Cv))) + # do percentage here
  geom_point()+
  geom_line()+
  theme_bw()+
  labs(x="Days",y="Cummulative Germination Percent (%)")+
  facet_wrap (~Temp,ncol=6, scales = "free")+
  ylim (0,100)+
  xlim(0,14)+
  geom_abline(intercept = 50, slope = 0)
#facet_grid(.~Temp, ncol=4, scales = "free")

head(df_seed)

```





