---
title: "Hardseeds 6CV"
author: "CT"
date: "Thursday, FEbruary 3, 2015"
output: html_document
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)

```


```{r loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\Gitsubclover")
getwd()

#create file
df_seed <- read.table("HardseedsData.txt",header=TRUE)
head(df_seed)
# Jeito 1 de trocar formato (usando base R)
df_seed$Date <- dmy(df_seed$Date)

# jeito 2 de trocar formato (usando dplyr)
df_seed <- df_seed %>%
  mutate(Plot = as.factor(Plot), Block = as.factor(Block))%>%
#  mutate(PropSoft =round((Soft/SeedNumber)*100),2)
  mutate(PropSoft = round(Soft/SeedNumber*100,digits=2))

summary(df_seed) # explore values
str(df_seed) # check formats
head(df_seed) # see to rows
tail(df_seed)

```


```{rCreate Percent Soft}

g1 <- df_seed %>%
  dplyr::select(-Date) %>%
  group_by(SowTreat,Cultivar,Depth, Plot) %>% # need to keep level in which cumulation occurs
  arrange(Round) %>% # need to tell which factor to accumulate within
  mutate(Soft_cum = cumsum(Soft)) %>%
  mutate(PercSoftCum=Soft_cum/max(SeedNumber))%>%
  group_by(SowTreat,Cultivar,Depth, Round) %>%
  summarise_each(funs(mean)) 

# per round
g1 %>%
 # filter(SowTreat == "S1") %>%
  ggplot(aes(x=Round,y=1-PercSoftCum,colour=factor(Cultivar)))+
  geom_point() +
  geom_line() +
  labs(x="Hardseed Assessment",y="Cummulative Proportion Hardseeds") +
  ylim(0,1)+
  facet_grid(SowTreat~Depth)


# xy up down comparison
g1 %>%
  dplyr::select(Plot,PercSoftCum,Depth,Round) %>%
  tidyr::spread(Depth, PercSoftCum)%>%
  ggplot(aes(x=down,y=up,colour=factor(Cultivar)))+
  geom_point() +
  facet_grid(SowTreat~.)

#Check for outliers _Boxplot 
df_seed %>%
  ggplot(aes(x=Cultivar, y=Soft, colour=factor(SowTreat)))+
  geom_boxplot() +
  geom_jitter() +
  theme(axis.text.x=element_text(angle = +90, hjust = 0))+
  facet_grid(Depth~Round+SowTreat)

```



Graph date Propsoft  

```{r Graph}



df_seed %>%
  select(SowTreat, Date,Block, Cultivar,PropSoft) %>%
  ggplot (aes(x=SowTreat,y=PropSoft)) +
  geom_point(aes(colour = Block)) +
  facet_grid(Block ~ Cultivar)
  
#Graph seedsoft for S1, rounds 1 2 and 3
head(df_seed)
  df_seed %>%
  select(SowTreat, Date,Block, Cultivar,Round, PropSoft)%>%
  ggplot (aes(x=Round,y=PropSoft)) +
  geom_point(aes(colour = SowTreat)) +
  facet_grid(Block ~ Cultivar)
  
  
```


```{r}
#Sum up the PropSoft starting form Round 1 (minimum soft) then round 2 and 3 
#Fix here 

head(df_seed)
  df_seed %>%
  mutate(SumPropSoft = cumsum(PropSoft))
  
```




Calculate the mean and error bars for each cultivar 

```{r}
df_seed %>%
  mutate(hardSeed = 100-PropSoft) %>%
  mutate(SowingD = dmy(SowingD)) %>%
  filter(Round == 1) %>%
  group_by(Cultivar,SowingD) %>%
  dplyr::select(hardSeed) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=SowingD, y=mean, colour=factor(Cultivar), shape=factor(Cultivar))) +
  geom_point() +
  geom_line() +
 facet_grid(.~Cultivar) +
  labs(x="Sowing Date",y="Maximum Percentage of Hardseeds") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2))+
  ylim(0,100)

head(df_seed)

df_seedANOVA <- df_seed %>%
mutate(hardSeed = 100-PropSoft) %>%
filter(Round == 1) 



#ANOVA

#data transformation
df_seedANOVA$transf_no <- 1*(df_seedANOVA$hardSeed)
df_seedANOVA$transf_sqr <- sqrt(df_seedANOVA$hardSeed)
df_seedANOVA$transf_log <- log(df_seedANOVA$hardSeed)
df_seedANOVA$transf_acos <- acos(df_seedANOVA$hardSeed/100)

head(df_seedANOVA)

file <- df_seedANOVA

x <- c( "transf_no",  "transf_sqr", "transf_log", "transf_acos")
colsSelec <- match(x,colnames(file))

file %>%
  tidyr::gather("transformation","value",colsSelec) %>%
  ggplot(aes(value)) + 
  geom_histogram() +
  facet_grid(.~transformation, scales="free")

head(file)

#normality test
#tranform log was the best histogram so continue with it 
shapiro.test(file$transf_log)

#QQplot
var<-file$transf_log
qqnorm(var)
qqline(var, col = 2)
qqplot(var, rt(300))

#-------------------------------------------------

# Chosen transform log to do anova 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_acos ~ Cultivar*SowTreat + Block, data = file.subset)

summary(my.anova)
TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar","SowTreat"), alpha= 0.05, p.adj="none")) 


```



