---
title: "Flowering 6CV"
author: "CT"
date: " June 07 2016"
output: html_document
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)

```


```{r loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover")
getwd()

#create file
df_Hvst <- read.table("DAStoHarvest.txt",header=TRUE)
head(df_Hvst)

df_Hvst$ReadingDate <- dmy(df_Hvst$ReadingDate )
df_Hvst$SowingD <- dmy(df_Hvst$SowingD)
df_Hvst$SowTreat <- as.factor(df_Hvst$SowTreat)
df_Hvst$Block <- as.factor(df_Hvst$Block)
df_Hvst$Plot <- as.factor(df_Hvst$Plot)
    

str(df_Hvst)
head(df_Hvst)
summary(df_Hvst)
tail(df_Hvst)



```





```{r GraphBoxPlotBud}

head(df_Hvst)

 df_Hvst %>%
  group_by(DAS, Cultivar,SowTreat, SowingD)%>%
  summarise_each(funs(mean)) %>%
  select(DAS, Cultivar,SowingD, SowTreat)%>%
  #filter(Variable == "Bud") %>%
  ggplot(aes(x=SowingD, y=DAS)) + 
  geom_point(aes(shape=Cultivar)) +
  geom_line(aes(colour=Cultivar))+
  #facet_grid(SowTreat~., scales = "free")+
  #facet_grid(Cultivar~., scales = "free")+
  #geom_abline(intercept = 50, slope = 0) +
  #ylim(0,210)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))




```


```{r ANOVA}

shapiro.test(df_Hvst$DAS)

my.anova <- aov(DAS ~ Cultivar*SowTreat + Block, data = df_Hvst)
summary(my.anova)
TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar","SowTreat"), alpha= 0.05, p.adj="none")) 


```







