---
title: "Analysis Seed density, TSW, seed per m2"
author: "CT"
date: " July 20, 2016"
output: html_document
---



```{r}
#Load libraries 
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(lubridate)
```

Read File 

```{r, echo=FALSE}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\Gitsubclover")
getwd()
file <- read.table("SeedDense.txt",header=TRUE)
head(file)
summary(file)
```

Calculations 

```{r}

# define factors and formats
file <- file %>%
  mutate(
    Plot = as.factor(Plot),
    Block = as.factor(Block),
    Cultivar = as.factor(Cultivar),
    Layer = as.factor(Layer),
    SowTreat = as.factor (SowTreat)
    
  )

str(file)
summary(file)

```

Seeds per Burr 

```{r}

# Seeds per Burr 

#barplot TSW 
#The palette with grey:
cbPalette <- c("#999999", "#666666", "#56B4E9", "#009E73", "#D55E00", "#0072B2","#999999", "#E69F00", "#56B4E9", "#009E73", "#D55E00", "#0072B2","#56B4E9", "#009E73")


# define position of bar and errorbar
dodge_x <- position_dodge(width = 0.9)




 file %>%
  group_by(Cultivar, SowTreat, Layer) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=Cultivar, y=(Seedsperbur_mean))) +
  geom_bar(stat="identity",position = dodge_x) +
  geom_errorbar(aes(ymin=Seedsperbur_mean-Seedsperbur_sd/2, ymax=Seedsperbur_mean+Seedsperbur_sd/2),
                width=0.25, size=0.3,position=dodge_x)   +
  theme_grey(base_size = 16) +
     facet_grid(Layer~SowTreat) +
    labs(y="Number of Seeds per Burr") +
theme(axis.text.x=element_text(angle = +89, hjust = 0.95))
head(file)


# ANOVA Seeds per Burr
#data transformation or not (1*)

file$transf_sqr <- sqrt(file$Seedsperbur)

file$transf_no <- 1*(file$Seedsperbur)


head(file)


x <- c("transf_sqr", "transf_no" )
colsSelec <- match(x,colnames(file))

file %>%
  tidyr::gather("transformation","value",colsSelec) %>%
  ggplot(aes(value)) + 
  geom_histogram() +
  facet_grid(.~transformation, scales="free")

head(file)

#normality test
shapiro.test(file$transf_no)

#QQplot
var<-file$transf_no
qqnorm(var)
qqline(var, col = 2)
qqplot(var, rt(300))

#-------------------------------------------------
# ANOVA 

file.subset <- file 

head(file.subset, 80)
summary(file.subset)
my.anova <- aov(transf_no ~ Layer*Cultivar*SowTreat + Block, data = file.subset)

summary(my.anova)
TukeyHSD(my.anova)



#Means separation 
(LSD.test(my.anova, "Layer", alpha= 0.05, p.adj="none")) 



```




TSW

```{r}

#barplot TSW 
#The palette with grey:
cbPalette <- c("#999999", "#666666", "#56B4E9", "#009E73", "#D55E00", "#0072B2","#999999", "#E69F00", "#56B4E9", "#009E73", "#D55E00", "#0072B2","#56B4E9", "#009E73")


# define position of bar and errorbar
dodge_x <- position_dodge(width = 0.9)




 file %>%
  group_by(Cultivar, SowTreat, Layer) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=Cultivar, y=(TSW_g_mean))) +
  geom_bar(stat="identity",position = dodge_x) +
  geom_errorbar(aes(ymin=TSW_g_mean-TSW_g_sd/2, ymax=TSW_g_mean+TSW_g_sd/2),
                width=0.25, size=0.3,position=dodge_x)   +
  theme_grey(base_size = 16) +
     facet_grid(Layer~SowTreat) +
    labs(y="TSW") +
theme(axis.text.x=element_text(angle = +89, hjust = 0.95))
head(file)

#ANOVA TSW 

#data transformation or not (1*)

file$transf_sqr <- sqrt(file$TSW_g)

file$transf_no <- 1*(file$TSW_g)


head(file)


x <- c("transf_sqr", "transf_no" )
colsSelec <- match(x,colnames(file))

file %>%
  tidyr::gather("transformation","value",colsSelec) %>%
  ggplot(aes(value)) + 
  geom_histogram() +
  facet_grid(.~transformation, scales="free")

head(file)

#normality test
shapiro.test(file$transf_no)

#QQplot
var<-file$transf_no
qqnorm(var)
qqline(var, col = 2)
qqplot(var, rt(300))

#-------------------------------------------------
# ANOVA 

file.subset <- file 

head(file.subset, 80)
summary(file.subset)
my.anova <- aov(transf_no ~ Layer*Cultivar*SowTreat + Block, data = file.subset)

summary(my.anova)
TukeyHSD(my.anova)



#Means separation 
(LSD.test(my.anova, "Cultivar", alpha= 0.05, p.adj="none")) 



```

Seed density (seeds per m2)
```{r}


#barplot Seedperm2

#The palette with grey:
cbPalette <- c("#999999", "#666666", "#56B4E9", "#009E73", "#D55E00", "#0072B2","#999999", "#E69F00", "#56B4E9", "#009E73", "#D55E00", "#0072B2","#56B4E9", "#009E73")


# define position of bar and errorbar
dodge_x <- position_dodge(width = 0.9)




 file %>%
  group_by(Cultivar, SowTreat, Layer) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=Cultivar, y=(Seedsperm2_mean))) +
  geom_bar(stat="identity",position = dodge_x) +
  geom_errorbar(aes(ymin=Seedsperm2_mean-Seedsperm2_sd/2, ymax=Seedsperm2_mean+Seedsperm2_sd/2),
                width=0.25, size=0.3,position=dodge_x)   +
  theme_grey(base_size = 16) +
     facet_grid(Layer~SowTreat) +
    labs(y="Seeds per m2") +
theme(axis.text.x=element_text(angle = +89, hjust = 0.95))
head(file)

#ANOVA Seedsperm2 

#data transformation or not (1*)

file$transf_sqr <- sqrt(file$Seedsperm2)

file$transf_no <- 1*(file$Seedsperm2)


head(file)


x <- c("transf_sqr", "transf_no" )
colsSelec <- match(x,colnames(file))

file %>%
  tidyr::gather("transformation","value",colsSelec) %>%
  ggplot(aes(value)) + 
  geom_histogram() +
  facet_grid(.~transformation, scales="free")

head(file)

#normality test
shapiro.test(file$transf_sqr)

#QQplot
var<-file$transf_sqr
qqnorm(var)
qqline(var, col = 2)
qqplot(var, rt(300))

#-------------------------------------------------
# ANOVA 

file.subset <- file 

head(file.subset, 80)
summary(file.subset)
my.anova <- aov(transf_no ~ Layer*Cultivar*SowTreat + Block, data = file.subset)

summary(my.anova)
TukeyHSD(my.anova)



#Means separation 
(LSD.test(my.anova, "SowTreat", alpha= 0.05, p.adj="none")) 
```


Grams seeds per m2 


```{r}
##barplot gSeeds perm2

#The palette with grey:
cbPalette <- c("#999999", "#666666", "#56B4E9", "#009E73", "#D55E00", "#0072B2","#999999", "#E69F00", "#56B4E9", "#009E73", "#D55E00", "#0072B2","#56B4E9", "#009E73")


# define position of bar and errorbar
dodge_x <- position_dodge(width = 0.9)




 file %>%
  group_by(Cultivar, SowTreat, Layer) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=Cultivar, y=(gseedsperm2_mean))) +
  geom_bar(stat="identity",position = dodge_x) +
  geom_errorbar(aes(ymin=gseedsperm2_mean-gseedsperm2_sd/2, ymax=gseedsperm2_mean+gseedsperm2_sd/2),
                width=0.25, size=0.3,position=dodge_x)   +
  theme_grey(base_size = 16) +
     facet_grid(Layer~SowTreat) +
    labs(y="Grams seeds per m2") +
theme(axis.text.x=element_text(angle = +89, hjust = 0.95))
head(file)

#ANOVA grams of seedsperm2 

#data transformation or not (1*)

file$transf_sqr <- sqrt(file$Seedsperm2)

file$transf_no <- 1*(file$Seedsperm2)


head(file)


x <- c("transf_sqr", "transf_no" )
colsSelec <- match(x,colnames(file))

file %>%
  tidyr::gather("transformation","value",colsSelec) %>%
  ggplot(aes(value)) + 
  geom_histogram() +
  facet_grid(.~transformation, scales="free")

head(file)

#normality test
shapiro.test(file$transf_sqr)

#QQplot
var<-file$transf_sqr
qqnorm(var)
qqline(var, col = 2)
qqplot(var, rt(300))

#-------------------------------------------------
# ANOVA 

file.subset <- file 

head(file.subset, 80)
summary(file.subset)
my.anova <- aov(transf_no ~ Layer*Cultivar*SowTreat + Block, data = file.subset)

summary(my.anova)
TukeyHSD(my.anova)



#Means separation 
(LSD.test(my.anova, "SowTreat", alpha= 0.05, p.adj="none")) 

```





