
---
title: "ThermalTime"
author: "CT"
date: "Friday, January 01, 2016"
output: html_document
---


```{r}
library(tidyr)
library (dplyr)
library (ggplot2)
library (lubridate)
```

Note: the file is called HistoricMeanTemp but actually contains the hobologger data Iversen 2


```{r}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover")
getwd()
df_file <- read.table("HistoricMeanTemp.txt", header=TRUE)

head(df_file)

#keep this scirpt for the real weather data

#df_Airjune <- read.table("MeanAirTMidJune.txt",header=TRUE)
#head(df_Airjune)
#df_file <- read.table("LoggerTemp.txt",header=TRUE)
#head(df_file)

#df_file <- rbind(df_Airjune,df_file)
#head(df_file,20)


```



```{r}
#Calculat Mean Air Temp

df_file$Date <- dmy(df_file$Date)

df_file <- df_file%>%
group_by(Date)%>%
summarise_each(funs(mean))
head(df_file)

#graph meanAir Temp

df_file %>% 
ggplot(aes(x=Date, y= Air)) +
    geom_line()
```



Calculate accumulated TT

```{r}

df_file <- df_file%>%
group_by(Date) %>%
summarise_each(funs(mean))%>%
  mutate(TT = cumsum(Air))%>%
 # dplyr::select(-hour,-Air)
  dplyr::select(-Air) # using I2 input

write.table(df_file, "ThermalSum.txt")

```


Graph it 


```{r graph}

df_file %>% 
ggplot(aes(x=Date, y= TT)) +
    geom_line()

```


