---
title: "Trifoliates Iversen "
author: "CT"
date: "31.08.2016"
output: html_document
---

Purpose:

-Analysis of trifoliates expansion for Iversen
- Graph the main dataset 
 
```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library (lubridate)
library(mosaic)
library(lattice)
```



```{r}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover\\TrifoCountsI2")
getwd()
#create file
df_trifo <- read.table("TrifoCountall.txt",header=TRUE)
head(df_trifo)


```
Define formats and calculate the mean number of trifoliates considering the sub samples (S1-S10)

```{r loadFile}


# define factors for the ones that "look like" values
df_trifo$Plot <- as.factor(df_trifo$Plot)
df_trifo$Block <- as.factor(df_trifo$Block)
df_trifo$Cultivar <- as.factor(df_trifo$Cultivar)
df_trifo$SowTreat <- as.factor(df_trifo$SowTreat)

 df_trifo <- df_trifo %>%
  mutate(SowingDate = dmy(SowingDate), 
         ReadingDate = dmy(ReadingDate),
         Trifo = (s1+s2+s3+s4+s5+s6+s7+s8+s9+s10)/10)

str(df_trifo)
head(df_trifo)
tail(df_trifo)


df_trifo %>% filter(Plot ==1) %>% summary()



```

Graph the results : DAS and number of trifoliates 

```{r, fig.height=5, fig.width=10}
#Graph         
  df_trifo %>%  group_by(Cultivar, SowTreat, DAS) %>%
  summarise_each(funs(mean)) %>%
  ggplot(aes(x=DAS, y=Trifo)) + 
  geom_point(aes(colour=Cultivar, shape=Cultivar)) +
  geom_line(aes(colour=Cultivar)) +
  facet_wrap(~SowTreat,ncol=4, scales = "free") +
  labs(y="Number of trifoliates",x="Days after sowing")+
  theme_bw()+
    #geom_abline(intercept = 6, slope = 0)
   geom_abline(intercept = 5, slope = 0)
```

Other graphics with same dat 
```{r}
#Graph         
  df_trifo %>%  group_by(Cultivar, SowTreat, DAS) %>%
  summarise_each(funs(mean)) %>%
  ggplot(aes(x=DAS, y=Trifo)) + 
  geom_point(aes(colour=Cultivar, shape=Cultivar)) +
  geom_line(aes(colour=Cultivar)) +
  facet_grid (SowTreat~., scales = "free")+
  labs(y="Number of trifoliates",x="Days after sowing")+
    #geom_abline(intercept = 6, slope = 0)
   geom_abline(intercept = 4:6, slope = 0)


#Graph2 (better?)         
  df_trifo %>%  group_by(Cultivar, SowTreat, DAS) %>%
  summarise_each(funs(mean)) %>%
  ggplot(aes(x=DAS, y=Trifo)) + 
  geom_point(aes(colour=Cultivar, shape=Cultivar)) +
  geom_line(aes(colour=Cultivar)) +
facet_wrap (~SowTreat,ncol=4, scales = "free")+
  labs(y="Number of trifoliates",x="Days after sowing")+
    theme_bw()+
    #geom_abline(intercept = 6 slope = 0)
  geom_abline(intercept = 4:6, slope = 0)

```

compare sowing dates 


```{r}
#Graph 

  df_trifo %>%  group_by(Cultivar, SowTreat, DAS) %>%
  summarise_each(funs(mean)) %>%
  ggplot(aes(x=DAS, y=Trifo)) + 
  geom_point(aes(shape=SowTreat,colour=SowTreat)) +
  geom_line(aes(colour=SowTreat)) +
  #facet_grid (SowTreat~., scales = "free")+
  theme_bw()+
  labs(y="Number of trifoliates",x="Days after sowing")+
    geom_abline(intercept = 6, slope = 0)

```

End of this script Calc 1. 
Move to script 2 to calculate percent and rate of leaf appearance 
