---
title: "Seed Scarification Analysis"
author: "CT"
date: "June, 2, 2016"
output: html_document
---
This script :
analyses rub test file



```{r}
#Load libraries 
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(lubridate)
```

Read File 

```{r, echo=FALSE}

setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\RubTest")
getwd()
file <- read.table("RubTest.txt",header=TRUE)
head(file)
summary(file)
```

Calculations 

```{r}

# define factors and formats
file <- file %>%
  mutate(
    Treat = as.factor(Treat),
    Rep = as.factor(Rep),
    CV = as.factor(CV))
    

str(file)
summary(file)
head(file)

```


```{r}

df<- file %>%
  mutate(HardSeedsPercent = 100-((Softseeds/Seeds)*100)) %>%
  dplyr::select(CV,Treat,
                Rep,HardSeedsPercent)

  df <- as.data.frame(df)
head(df)

```

```{r}

#barplot for seed density  
#The palette with grey:
cbPalette <- c("#999999", "#666666", "#56B4E9", "#009E73", "#D55E00", "#0072B2","#999999", "#E69F00", "#56B4E9", "#009E73", "#D55E00", "#0072B2","#56B4E9", "#009E73")


# define position of bar and errorbar
dodge_x <- position_dodge(width = 0.9)

summary (df)
str(df)

# splitting and df due bug in tidyr (https://github.com/hadley/tidyr/issues/32)
 df %>%
  group_by(CV, Treat) %>%
   dplyr::select(-Rep) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=CV, y=(mean), fill=Treat)) +
  geom_bar(stat="identity",position = dodge_x) +
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2),
                width=0.25, size=0.3,position=dodge_x)   +
  theme_grey(base_size = 16) +
    theme_bw()+
  #facet_grid(Depth~SowTreat, scales="free") +
    labs(y= "Percent Hardseeds")+
   labs(x="Cultivar")+
theme(axis.text.x=element_text(angle = +90, hjust = 0))+
  theme(text = element_text(size = 14))


```

Stats here !
