---
title: "Emergence seedlings I2"
author: "CT"
date: "Thursday, December 31, 2015"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

Purpose:

-Analysis of plant population 
-calculate the percentage of emergence 



```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(mosaic)
library(lattice)
```


```{r loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover\\EmergenceIv2")
getwd()

#create file
df_emerg <- read.table("PlantPop.txt",header=TRUE)

# define factors for the ones that "look like" values
df_emerg$Plot <- as.factor(df_emerg$Plot)
df_emerg$Block <- as.factor(df_emerg$Block)

 df_emerg <- df_emerg %>%
  mutate(SowingDate = dmy(SowingDate), 
         ReadingDate = dmy(ReadingDate),
         PlantPop = (Sub1+Sub2+Sub3)/3/0.01)

str(df_emerg)
head(df_emerg)
tail(df_emerg)


df_emerg %>% filter(Plot ==1) %>% summary()


```

```{r, fig.height= 5, fig.width= 10}
# Graph it 


#Graph         
  df_emerg %>%  group_by(Cultivar, SowTreat, DAS) %>%
  #filter(SowTreat =="S2"& SowTreat =="S4")%>%
  #dplyr::select(-SowingDate, - ReadingDate) %>%
  summarise_each(funs(mean)) %>%
  ggplot(aes(x=DAS, y=PlantPop)) + 
  geom_point(aes(colour=Cultivar,shape=Cultivar)) +
  geom_line(aes(colour=Cultivar)) +
  #add error bar
  geom_errorbar(aes(x=20,ymin=200,ymax=300,width=0.2))+
  facet_wrap(~SowTreat,ncol=4, scales = "free")+
  theme_bw()+
  ylim(0, 2200)+
  labs(y="Number of seedlings per m2",x="Days after sowing") +
  geom_abline(intercept = 1000, slope = 0)

```



```{r CalculatePercentageEmergence }

df_emerg_perc <- df_emerg %>%
group_by(Plot) %>%
mutate(PercEmerg = round(PlantPop/max(PlantPop)*100,digits=2))

# Check
summary(df_emerg_perc)
tail(df_emerg_perc)
df_emerg_perc %>%  filter(Plot=="2")


```

```{r, fig.width= 10, fig.height=7}
#Graph         
  df_emerg_perc %>%  group_by(Cultivar, SowTreat, DAS) %>%
#  filter(Cultivar =="Monti") %>%
  dplyr::select(-SowingDate, - ReadingDate) %>%
  summarise_each(funs(mean)) %>%
  ggplot(aes(x=DAS, y=PercEmerg)) + 
  geom_point(aes(colour=Cultivar,shape=Cultivar)) +
  geom_line(aes(colour=Cultivar)) +
    theme_bw()+
  facet_wrap (~SowTreat,ncol=4, scales = "free")+
  labs(y="Percentage  of Seedling emergence",x="Days after sowing") +
  geom_abline(intercept = 50, slope = 0)
```


```{r ANOVAMaxPlantPop}

#compare max plant population among Sowing dates and cultivars

df_emerg_perc3 <- df_emerg %>%
group_by(Plot) %>%
mutate(FinalPop= round(max(PlantPop)*1,digits=2))

head(df_emerg_perc3)
summary (df_emerg_perc3)

write.table(df_emerg_perc3, "df_emerg_perc3.txt")
```

then select each sowing date individually 


```{r}
df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S1") 
summary (df_emerg_S1)  
  
```



Run ANOVA pure numbers 

```{r}
#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)

#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))

```

S2
 
```{r}

df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S2") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)

#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))
```

S3

```{r}
df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S3") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)

#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))

```
S4


```{r}
df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S4") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)

#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))


```

S5


```{r}

df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S5") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)

#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))

```

S6

```{r}
df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S6") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)

#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))

```


S7 

```{r}

df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S7") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)

#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))

```
S8

```{r}
df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S8") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)

#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))
```

