---
title: "Emergence seedlings Poukawa"
author: "CT"
date: " March,  2016"
output: html_document
---

Purpose:

-Analysis of plant population 
-calculate the percentage of emergence 



```{r loadLibraries, warning=FALSE}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(mosaic)
library(lattice)
```


```{r loadFile, fig.height=5, fig.width= 10}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover\\EmergencePoukawa")
getwd()

#create file
df_emerg <- read.table("PlantPopPok.txt",header=TRUE)
head(df_emerg)

# define factors for the ones that "look like" values
df_emerg$Plot <- as.factor(df_emerg$Plot)
df_emerg$Block <- as.factor(df_emerg$Block)

 df_emerg <- df_emerg %>%
  mutate(SowingDate = dmy(SowingDate), 
         ReadingDate = dmy(ReadingDate),
         PlantPop = (Sub1+Sub2+Sub3)/3/0.01)

str(df_emerg)
head(df_emerg)
tail(df_emerg)


df_emerg %>% filter(Plot ==1) %>% summary()



```

```{r,fig.height=10, fig.width=10}}

#Graph         
  df_emerg %>%  group_by(Cultivar, SowTreat, DAS) %>%
#  filter(Cultivar =="Monti") %>%
  #dplyr::select(-SowingDate, - ReadingDate) %>%
  summarise_each(funs(mean)) %>%
  ggplot(aes(x=DAS, y=PlantPop)) + 
  geom_point(aes(colour=Cultivar)) +
  geom_line(aes(colour=Cultivar)) +
  # facet_grid (SowTreat~., scales = "free")+
    facet_wrap (~SowTreat,ncol=4, scales = "free")+
  theme_bw()+
  labs(y="Number of seedlings per m2",x="Days after sowing") 
  #+geom_abline(intercept = 50, slope = 0)

```





```{r CalculatePercentageEmergence, fig.height=5, fig.width= 10 }

df_emerg_perc <- df_emerg %>%
group_by(Plot) %>%
  mutate(PercEmerg = round(PlantPop/max(PlantPop)*100,digits=2))


# Check
summary(df_emerg_perc)
tail(df_emerg_perc)
df_emerg_perc %>%  filter(Plot=="2")





 #Graph         
  df_emerg_perc %>%  group_by(Cultivar, SowTreat, DAS) %>%
#  filter(Cultivar =="Monti") %>%
  dplyr::select(-SowingDate, - ReadingDate) %>%
  summarise_each(funs(mean)) %>%
  ggplot(aes(x=DAS, y=PercEmerg)) + 
  geom_point(aes(colour=Cultivar)) +
  geom_line(aes(colour=Cultivar)) +
  facet_wrap (~SowTreat,ncol=4, scales = "free")+
  labs(y="Percentage  of Seedling emergence",x="Days after sowing") +
    theme_bw()+
  geom_abline(intercept = 50, slope = 0)

```


```{r ANOVAMaxPlantPop}

#compare max plant population among Sowing dates and cultivars

df_emerg_perc3 <- df_emerg %>%
group_by(Plot) %>%
mutate(FinalPop= round(max(PlantPop)*1,digits=2))

head(df_emerg_perc3)
summary (df_emerg_perc3)


#normality test
shapiro.test(df_emerg_perc3$FinalPop)


#data transformation
file <- df_emerg_perc3

file$transf_sqr <- sqrt(df_emerg_perc3$FinalPop)
file$transf_log <- log(df_emerg_perc3$FinalPop)
file$transf_log1 <- log(df_emerg_perc3$FinalPop+1)
file$transf_no <- 1*(df_emerg_perc3$FinalPop)
head(file)



x <- c("transf_sqr", "transf_log","transf_log1", "transf_no")
colsSelec <- match(x,colnames(file))

file %>%
  tidyr::gather("transformation","value",colsSelec) %>%
  ggplot(aes(value)) + 
  geom_histogram() +
 # facet_wrap(SowTreat~transformation, scales="free", ncol=4) +
  facet_grid(transformation~SowTreat, scales="free")

head(file)


#QQplot
# var<-file$transf_no
# qqnorm(var)
# qqline(var, col = 2)
# qqplot(var, rt(300))

#-------------------------------------------------
# ANOVA (selecing by hand FIXME: do loop)
# file.subset <- file %>% subset(SowTreat == "S2" & round==1)
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar*SowTreat + Block, 
                data = file.subset)

summary(my.anova)

TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("SowTreat"), alpha= 0.05, p.adj="none") ) 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
(LSD.test(my.anova, c("SowTreat","Cultivar"), alpha= 0.05, p.adj="none"))


```




Do not have soil Temperature for Poukawa ...used Air Temp skip this script 

```{r}

#empthy chunk

```



```{r SoilTemp}
# df_CumTT.txt is generated in folder PokWeather... basically here is the same as per TT because do not have soil Temp
#Remember to format dates as ymd 

df_SoilTT <- read.table("ThermalSumSoilPo.txt",header=TRUE)
head(df_SoilTT)

# convert to date format

df_SoilTT <- as.data.frame(df_SoilTT) %>%
 mutate(Date=ymd(Date))


# check
head(df_SoilTT)


```

Merge the dataframes 

```{r}

# Merge Tt at measurement date
df_emerg_perc_TT <- NULL
df_emerg_perc_TT <- merge(df_emerg_perc,df_SoilTT,by.x="ReadingDate",by.y="Date")
df_emerg_perc_TT <- merge(df_emerg_perc_TT,df_SoilTT,by.x="SowingDate",by.y="Date")

df_emerg_perc_TT$TT_to_emerg <- df_emerg_perc_TT$TT.x-df_emerg_perc_TT$TT.y
summary(df_emerg_perc_TT)

#save as table 
write.table(df_emerg_perc_TT, "df_emerg_perc_soilTTPo.txt")
head(df_emerg_perc_TT )

# graph emerg x tt
df_emerg_perc_TT %>%
  group_by(Cultivar, SowTreat, TT_to_emerg) %>%
  #dplyr::select(-SowingDate, - ReadingDate) %>%
#  filter(Cultivar =="Narrikup") %>%
  summarise_each(funs(mean)) %>%
  ggplot(aes(x=TT_to_emerg, y=PercEmerg,colour=Cultivar)) + 
  geom_point() +
  geom_line() +
  #facet_grid (Cultivar~., scales = "free")+
  geom_abline(intercept = 50, slope = 0) +
  facet_wrap (~SowTreat,ncol=4, scales = "free")+
  xlab("Thermal-time from sowing") +
  ylab("Percentage emergence")


```


End of this script ...continue in Pok_Calc2