---
title: "Spectra of S2 FTIR test"
author: "CT"
date: "21 March 2017"
output: html_document
#here files have already been baselined corrected in OPUS. Raw data is on folder Bionami Maatrix 25.04; worksheet Columns to R. 
---


```{r setup, include=FALSE, loadlibraires}
#knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(scales)
library(hyperSpec)

```



```{r}
#package installed

 #install.packages ("hyperSpec")
```



```{r readData}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\FTIR_S2")
getwd()
file <- read.table ("S2.txt",  header = TRUE)

str (file)

```
Adjust formats 

```{r}

file1 <-file %>%
mutate(
    Plot = as.factor(Plot),
    wavelength = as.integer(wavelength), # leave as integer for graphics  
    Block = as.factor(Block),
    Cultivar = as.factor(Cultivar),
    Hardness = as.numeric (Hardness),
    Seed = as.factor(Seed)
  )  

str (file1)


```
## Graph it all data 

```{r, fig.height=4, fig.width=10}

file1 %>%
  
  ggplot(aes(x=wavelength,y=Absorbance))+
  geom_line(aes(colour=Cultivar))+
  theme_bw()+
scale_x_continuous(breaks=seq(min(file1$wavelength),max(file1$wavelength),100))+
  scale_x_reverse()+
  #scale_x_continuous(lim=c(650,4000))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  expand_limits(y=c(0,0.2)) +
  #expand_limits(x=650, 4000)+
  geom_abline(intercept = 0.1, slope = 0)


```
Graph average spectra for each cultivar 


```{r, fig.height=5, fig.width=10}

file1 %>%
  dplyr::select(Cultivar,Absorbance, wavelength)%>%
  group_by(Cultivar,wavelength)%>%
  summarise_each(funs(mean))%>%
  filter(Cultivar=="Monti"|Cultivar=="Woogenellup")%>%
  ggplot(aes(x=wavelength,y=Absorbance, colour=Cultivar))+
           geom_line()+
  theme_bw()+
 #scale_x_continuous(breaks=seq(min(file1$wavelength),max(file1$wavelength),100))+
  #scale_x_reverse()+
  scale_y_continuous(breaks = seq(0, 0.16, by = 0.02))+
  scale_x_continuous(breaks = seq(650, 4000, by = 100))+
  scale_x_reverse(breaks = seq(650, 4000, by = 100))+
  #scale_x_continuous(lim=c(650,4000))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  #expand_limits(y=c(0,0.14)) +
  scale_y_continuous(breaks = seq(0, 0.14, by = 0.02))+
 xlab(expression(Wavenumber~"(cm"^"-1"*")"))
  #expand_limits(x=650, 4000)+
  #geom_abline(intercept = 0.1, slope = 0)
  
  


```
End of this script. Analysis continue in script 2  



