---
title: "Spectra of S2 FTIR test"
author: "CT"
date: "21 March 2017"
output:   
  word_document: default
  pdf_document: default
  html_document: default
#here files have already been baselined corrected in OPUS. Raw data is on folder Bionami Maatrix 25.04; worksheet Columns to R. In this script the analysis of wavenumber range 3500 and 3200 is performed. find peak in this region.l  
---


```{r setup, include=FALSE, loadlibraires}
#knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(scales)
library(hyperSpec)

```


```{r readData}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\FTIR_S2")
getwd()
file <- read.table ("S2.txt",  header = TRUE)

str (file)

```
Adjust formats 

```{r}

file1 <-file %>%
mutate(
    Plot = as.factor(Plot),
    #wavelength = leave as integer for greaphics 
    Block = as.factor(Block),
    Cultivar = as.factor(Cultivar),
    Hardness = as.numeric (Hardness),
    Seed = as.factor(Seed)
  )  

str (file1)


```
Subset a range of interest: between 3500 and 3200


```{r}

df_a<-file1 %>%
  #subset range 3500-3200
  subset (wavelength>650 & wavelength<3997)

```

## Graph it all data 

```{r, fig.height=4, fig.width=10}

df_3200 %>%
  
  ggplot(aes(x=wavelength,y=Absorbance))+
  geom_line(aes(colour=Cultivar))+
  theme_bw()+
scale_x_continuous(breaks=seq(min(file1$wavelength),max(file1$wavelength),10))+
  scale_x_reverse()+
  #scale_x_continuous(lim=c(650,4000))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  expand_limits(y=c(0,0.005)) +
  #expand_limits(x=650, 4000)+
  geom_abline(intercept = 0.1, slope = 0)


```
Graph average spectra for each cultivar 


```{r}

df_3200 %>%
  dplyr::select(Cultivar,Absorbance, wavelength)%>%
  group_by(Cultivar,wavelength)%>%
  summarise_each(funs(mean))%>%
  #filter(Cultivar=="Monti"|Cultivar=="Woogenellup")%>%
  ggplot(aes(x=wavelength,y=Absorbance, colour=Cultivar))+
           geom_line()+
  theme_bw()+
scale_x_continuous(breaks=seq(min(file1$wavelength),max(file1$wavelength),100))+
  scale_x_reverse()+
  #scale_x_continuous(lim=c(650,4000))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  expand_limits(y=c(0,0.005)) +
 xlab(expression(Wavenumber~"(cm"^"-1"*")"))+
  #expand_limits(x=650, 4000)+
  geom_abline(intercept = 0.1, slope = 0)
  
  


```
identified peak 3330. subset data for this peak   

```{r}

df_3330 <-file1 %>%
  #subset range 3500-3200
  subset (wavelength==3330)
  

```

Now with the subset run ANOVA

```{r}
file.subset <- df_a 

head(file.subset)
summary(file.subset)

```

```{r}
#ANOVA
my.anova <- aov(Absorbance ~ Cultivar + Block, data = file.subset)
#my.anova <- aov(Absorbance ~ Cultivar*Seed + Block, data = file.subset)

summary(my.anova)
```



```{r}

(LSD.test(my.anova, c( "Cultivar"), alpha= 0.05, p.adj="none"))

```

wavenumber 33


```{r}
df_3951 <-file1 %>%
  #subset range 3500-3200
  subset (wavelength==3951)
```


```{r}
file.subset <- df_3951 

head(file.subset)
summary(file.subset)
```


```{r}
#ANOVA
my.anova <- aov(Absorbance ~ Cultivar + Block, data = file.subset)
#my.anova <- aov(Absorbance ~ Cultivar*Seed + Block, data = file.subset)

summary(my.anova)
```

```{r}
(LSD.test(my.anova, c( "Cultivar"), alpha= 0.05, p.adj="none"))
```



End of this script. Analysis continue in Script 3.

