---
title: "MinMaxTemp"
author: "CT"
date: "Wednesday, January 06, 2016"
output: 
  word_document: default
  pdf_document: default
  html_document: default
---

Graphing Max, Min and Average temperatures field experiment with 6 cvs.  

```{r LoadLibraries }
library(knitr)
library(tidyr)
library (dplyr)
library (ggplot2)
library (lubridate)
library (reshape2)
```

REad table Notepad file: Temperatures Cold Test FieldExp_2

```{r, readFile}

setwd("C:\\Users\\Ed\\Documents\\Subclovergit\\Temperatures Cold test")
getwd()

#create file
df_Ttwo <- read.table("FieldExp_2.txt",header=TRUE)
df_Ttwo
head(df_Ttwo)
summary (df_Ttwo)
tail(df_Ttwo)
```

Create Graph : convert date into dmy


```{r createFileExpOne}

df_Ttwo$Date <- dmy(df_Ttwo$Date)
#df_Tone_long <- melt(df_Tone, id="Date")

df_Ttwo %>%
ggplot(aes(x=Date)) +
    geom_line(aes(y= Taverage, colour = "MeanT"))+
    geom_line(aes(y = Tmin, colour = "MinT"))+
    geom_line(aes(y = Tmax, colour = "MaxT"))+
    ylab("Temperature")+
    theme_bw()+
    ggtitle("Field Experiment3 Daily Temperature (oC) ")

```
Calculate TT

```{r calculateTT}

Tb <-0 #base temperature oC 

df_Ttwo <- df_Ttwo %>%
  mutate(TT=Taverage-Tb)
head(df_Ttwo)
```



