---
title: "MinMaxTemp"
author: "CT"
date: "Wednesday, January 06, 2016"
output: 
  word_document: default
  pdf_document: default
  html_document: default
---

Graphing Max, Min and Average temperatures 

```{r LoadLibraries }
library(knitr)
library(tidyr)
library (dplyr)
library (ggplot2)
library (lubridate)
library (reshape2)
```

REad table Notepad file: Temperatures Cold Test GH outdoor

```{r, readFile}

setwd("C:\\Users\\Ed\\Documents\\Subclovergit\\Temperatures Cold test")
getwd()

#create file
df_Three <- read.table("Exp2_pots.txt",header=TRUE)
df_Three
head(df_Three)
summary (df_Three)
tail(df_Three)
```

Create Graph : convert date into dmy


```{r createFileExpOne}

df_Three$Date <- dmy(df_Three$Date)
#df_Tone_long <- melt(df_Tone, id="Date")

df_Three %>%
ggplot(aes(x=Date)) +
    geom_line(aes(y= Taverage, colour = "MeanT"))+
    geom_line(aes(y = Tmin, colour = "MinT"))+
    geom_line(aes(y = Tmax, colour = "MaxT"))+
    ylab("Temperature")+ 
    theme_bw()+
    ggtitle("GH Experiment outdoor Daily Temperature (oC) ")

```
Calculate TT

```{r calculateTT}

Tb <-0 #base temperature oC 

df_Three <- df_Three %>%
  mutate(TT=Taverage-Tb)
head(df_Three)


df_Three <- df_Three %>%
mutate(cs = cumsum(TT))
head(df_Three)
 

```



