---
title: "Spectrum Average  Test"
author: "CT"
date: "22 March 2017"
output: html_document. This script reads the average spectra txt and build panels 

---

```{r setup, include=FALSE, loadlibraires}
#knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(scales)

```



```{r readData}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover\\Spectra")
getwd()

#create file
df_sp <- read.table("AverageSpectra.txt",header=TRUE)

#head(df_sp)

summary(df_sp)
```

## Graph it 

```{r, fig.height=10, fig.width=10}

df_sp %>%
  ggplot(aes(x=Wavelenght,y=Absorbance))+
  #geom_line()+
  geom_line(aes(colour=Absorbance))+
  theme_bw()+
scale_x_continuous(breaks=seq(min(df_sp$Wavelenght),max(df_sp$Wavelenght),400))+
  facet_wrap(~Cultivar,scale="free")+
  #labs(x=" Wavelenght", y=" Absorbance")+
  #scale_color_manual(values=c("#333333", "#9999CC", "#CC3300"))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  expand_limits(y=c(0,0.2)) +
  geom_abline(intercept = 0.1, slope = 0)
  #scale_x_date(labels = date_format("%b-%Y"))


```

## Define Tt cardinal temperatures

Considered an overall average the following references:
Tb: 0.0
Top range:18-25
Tmax: 40
REFS: MonksEtAl2009	,LonatiEtAl2009	,MootEtal2003, SilsburyetAl1984. 
							


```{r}

#Create Thermal time cardinal temperatures need REF! 

tt_card <- data.frame(temp=c(0,18,25,40),TT=c(0,18,18,0))
tt_card %>%
  ggplot(aes(x=temp, y=TT))+
  labs(x="Temperature (degree Celsius)")+
  labs(y="Thermal Time (oCd)") +
  geom_line()
  
#FIX ME include REF Thermal time 
```

```{r}

#Create and test interpolation function - Test if works 

temp_ref  <- 25 # x-axes reference
temp <- tt_card$temp # x-axes
TT <- tt_card$TT # y-axes


int_func <- function(temp,TT,temp_ref){

  # if temp is too low or too high give extreme TT values
 if(temp_ref>temp[length(temp)]) {
   
   out <- TT[length(TT)] 
   # FIXME: approx functions seems to do that - need param
   
 } else if (temp_ref<temp[1]) {
   
   out <- TT[1]
   
 } else {
   
   # else interpolate
   
   tryCatch(  
   
  out <- approx(temp, TT, xout = temp_ref, 
         method="linear", 
         rule = 2)$y,
  error = function(e) 
  {
  out <- NA
  }
) 
  
} # end if check

  return(out)  
  
 }
  
int_func(temp,TT,temp_ref)


```

```{r}

#create REF Jones CA, Ritchie JT, Kiniry JR, Godwin DC (1986) Subroutine structure.In 'CERES-Maize: A simulation model of maize growth anddevelopment'. (Eds CA Jones, JR Kiniry) pp. 49-194. (Texas A&M University Press: Texas, USA

TTfunc <- function(Tmin ,Tmax){         
 
  if (Tmin>Tmax){
   print("Tmin>Tmax")
   break
 } 
  
  TTav  <- 0
  TTsum <- 0
  
  for(n in 1:8){ 
    
    tn <- 0
    
    TT_tn <- 0
    
    tn <- ((0.931 +  0.114*n - 0.0703 * n^2
            + 0.0053 * n^3) * (Tmax-Tmin)) + 
      Tmin # 8-h temperature
    
    TT_tn <- int_func(tt_card$temp, tt_card$T,tn) 
    
    TTsum <- TT_tn + TTsum
    
    print(TT_tn)
    
    }
  TTav <- TTsum/8
  
  return(TTav)
  }

TTfunc(10,30)

```

```{r ReadCalcTt}

df_We_tt <- df_We %>%
  mutate(TTday=TTfunc(Tm,Tx), TTday_s=(Tm+Tx)/2, diff=(TTday_s/TTday)*100)

```


```{r}
#Check TT 
df_We_tt  %>% 
ggplot(aes(x=TTday_s, y= TTday)) +
    geom_point(shape=21,alpha=0.2)+
  geom_abline(intercept = 0, slope = 1)

```





```{r}

#Calculate accumulated Themal time 

df_CumTT <- df_We_tt %>%
group_by(LocationYear) %>%
arrange(Date) %>%
mutate(SumTTday = cumsum(TTday)) %>%
mutate(DayCount=Date-min(Date))

head(df_CumTT)


```

```{r, fig.height=10, fig.width=10}
#Graph Accumulated TT 

df_CumTT %>%
  ggplot(aes(x=DayCount,y=SumTTday))+
  geom_line(aes(colour=LocationYear, linetype=Country)) +
  #facet_wrap(~LocationYear,scale="free") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlim(0,300)+
  ylim(0,5000)

```




```{r}

write.table(df_CumTT, "df_CumTT.txt")

```

