---
title: "compilation  Test"
author: "CT"
date: "22 March 2017"
output: html_document. This script reads the average spectra txt and build panels 

---

```{r setup, include=FALSE, loadlibraires}
#knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(scales)

```



```{r readData}

filePath <- ("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\Spectra\\testMicro")

# Test if there are not scraps of .csv files in folder
micro.files <- list.files(filePath,
                        pattern = '*.0', full.names=TRUE, 
                        recursive = TRUE, include.dirs = F) # if true gets path

all.the.data <- lapply(micro.files, read.table, header=FALSE, sep=",")
DATA <- do.call("rbind", all.the.data)

colnames(DATA) <- c("Wavelength", "Absorbance")

summary(DATA)

head(DATA, 10)


summary(DATA)
```

## Graph it 

```{r, fig.height=5, fig.width=10}

df_sp %>%
  ggplot(aes(x=Wavelenght,y=Absorbance))+
  #geom_line()+
  geom_line(aes(colour=Absorbance))+
  theme_bw()+
scale_x_continuous(breaks=seq(min(df_sp$Wavelenght),max(df_sp$Wavelenght),500))+
  #facet_wrap(~Cultivar,scale="free")+
  #labs(x=" Wavelenght", y=" Absorbance")+
  #scale_color_manual(values=c("#333333", "#9999CC", "#CC3300"))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  expand_limits(y=c(0,0.2)) +
  expand_limits(x=c(640,4000)) +
   scale_x_reverse()+
  geom_abline(intercept = 0.1, slope = 0)
  #scale_x_date(labels = date_format("%b-%Y"))


```

## now do for different seed regions Lateral and Ventral 

 
							


```{r}

#Create Thermal time cardinal temperatures need REF! 

tt_card <- data.frame(temp=c(0,18,25,40),TT=c(0,18,18,0))
tt_card %>%
  ggplot(aes(x=temp, y=TT))+
  labs(x="Temperature (degree Celsius)")+
  labs(y="Thermal Time (oCd)") +
  geom_line()
  
#FIX ME include REF Thermal time 
```

```{r}

#Create and test interpolation function - Test if works 



```

```{r}

#create REF Jones CA, Ritchie JT, Kiniry JR, Godwin DC (1986) Subroutine structure.In 'CERES-Maize: A simulation mo

```





```{r}

#Calculate accumulated Themal time 



```

```{r, fig.height=10, fig.width=10}
#Graph Accumulated TT 

```




```{r}



```

