---
title: "Spectrum Suberin Test"
author: "CT"
date: "21 March 2017"
output: html_document
---

```{r setup, include=FALSE, loadlibraires}
#knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(scales)

```



```{r readData}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\Spectra")
getwd()

#create file
df_sp <- read.table("suberinbaselined.txt",header=TRUE)

#head(df_sp)

str(df_sp)
```

## Graph it 



```{r}
df_sp <- df_sp %>%
mutate(wavelength = as.numeric(wavelength),
    Absorbance =  as.numeric(Absorbance))
    
```

Graph it but subset to make the same scale as per the seed coat spectrum 
```{r, fig.height=5, fig.width=10}

df_sp %>%
  subset (wavelength<3800 & wavelength>650)%>%
  ggplot(aes(x=wavelength,y=Absorbance))+
  geom_line(aes())+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_y_continuous(breaks = seq(0, 0.16, by = 0.02))+
  scale_x_continuous(breaks = seq(650, 3950, by = 100))+
  scale_x_reverse(breaks = seq(650, 3950, by = 100))+
  #expand_limits(y=c(0,0.2)) +
  xlab(expression(Wavenumber~"(cm"^"-1"*")"))
  geom_abline(intercept = 0.1, slope = 0)


```




#