---
title: "Proportion of dead and abnormal seedlings over total number of seeds _ 6CV"
author: "CT"
date: "Thursday, 25 October , 2016"
output: pdf_document
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(markdown)
#install.packages(markdown)

```


```{r loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\Gitsubclover\\Hardseeds")
getwd()

#create file
df_seed <- read.table("HardseedsLiveData.txt",header=TRUE)
head(df_seed)
# Jeito 1 de trocar formato (usando base R)
df_seed$Date <- dmy(df_seed$Date)

# jeito 2 de trocar formato (usando dplyr)
df_seed <- df_seed %>%
  mutate(Plot = as.factor(Plot), Block = as.factor(Block))%>%
  mutate(Soft = as.numeric(Soft),
         SoftDead = as.numeric(SoftDead),
         SoftGerm = as.numeric (SoftGerm),
         SoftAbn = as.numeric (SoftAbn),
         SoftUngerm = as.numeric (SoftUngerm)) %>%
  

summary(df_seed) # explore values
str(df_seed) # check formats
head(df_seed) # see to rows
tail(df_seed)



```



```{r CreatePercentDead}
#Create a column that is the Accumulated Dead this is to calculate the percentage of Dead seeds  


df_hard_live_max <- df_seed %>%
  mutate(Depth = factor(Depth,levels=c( "up","down")))%>%
  group_by(Plot,Depth) %>% 
  dplyr::select(-Date) %>% # 
  arrange(Round) %>% # need to tell which factor to accumulate within
  mutate(CumSoftDead = cumsum(SoftDead)) %>%
  #calculate the percentage of dead seeds  
  mutate(Total_live = InitialSeedlotR1Number-max(CumSoftDead)) %>%
   mutate(ProportionLive = ( Total_live/InitialSeedlotR1Number)) %>%
  #filter(Round==1) %>%
  mutate(Dead_perc = round(100-(Total_live/InitialSeedlotR1Number*100),2))

  
summary (df_hard_live_max)

head(df_hard_live_max)
summary(df_hard_live_max) # explore values


```


```{r}


#Create a column that is the Accumulated Abnormals this is to calculate the percentage of Abnormal seeds  


df_hard_live_abn <- df_seed %>%
  mutate(Depth = factor(Depth,levels=c( "up","down")))%>%
  group_by(Plot,Depth) %>% 
  dplyr::select(-Date) %>% # 
  arrange(Round) %>% # need to tell which factor to accumulate within
  mutate(CumSoftAbn = cumsum(SoftAbn)) %>%
  #calculate the percentage of dead seeds  
  mutate(Total_Abn = InitialSeedlotR1Number-max(CumSoftAbn)) %>%
   mutate(ProportionAbn = ( Total_Abn/InitialSeedlotR1Number)) %>%
  #filter(Round==1) %>%
  mutate(Abn_perc = round(100-(Total_Abn/InitialSeedlotR1Number*100),2))


summary (df_hard_live_abn)


#Graph the  percentage of dead seeds!!! 

  df_hard_live_abn %>%
  mutate(SowingD = dmy(SowingD)) %>%
  
  #filter(Round == 1) %>%
  group_by(Cultivar,SowingD, Depth) %>%
  dplyr::select(Abn_perc) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=SowingD, y=mean, colour=factor(Cultivar), shape=factor(Cultivar))) +
  geom_point() +
  geom_line() +
 facet_grid(Depth~Cultivar) +
  labs(x="Sowing Date",y=" Percentage of Abnormal Seeds (%)") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2))+
  ylim(0,50)



```




```{r}




  df_hard_live_max %>%
  mutate(SowingD = dmy(SowingD)) %>%
  
  #filter(Round == 1) %>%
  group_by(Cultivar,SowingD, Depth) %>%
  dplyr::select(Dead_perc) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=SowingD, y=mean, colour=factor(Cultivar), shape=factor(Cultivar))) +
  geom_point() +
  geom_line() +
 facet_grid(Depth~Cultivar) +
  labs(x="Sowing Date",y=" Percentage of Dead Seeds (%)") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2))+
  ylim(0,50)




```

