---
title: "CreateMergedPhenologyStages for Growth Chamber experiment "
author: "CT"
date: " January 20, 2017"
output:
  word_document: default
  pdf_document: default
  html_document: default
---


```{r loadLibraries,echo=FALSE}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)

```

Read and check formats and file 
```{r loadFile, include=FALSE}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\GCFlower")
getwd()

#create file
df_flower <- read.table("df_flower.txt",header=TRUE)

# tail(df_flower)
# 
# summary(df_flower)
# 
# df_flower %>%
# filter(S1>1)


```
check structure 
```{r}
str(df_flower)

## change name to standardise columns (Plot and Pot are the same )
df_flower <- df_flower %>%
  mutate (Plot=Pot)
```
Create a category that is flowering which contains early bud and petal. 

```{r}

# create df with flowering stages only (merged)
df_flower_simple <- df_flower %>%
  #mutate(Plot=Pot)%>%
filter(Variable == "Early" | 
         Variable == "Open" | 
         Variable == "Petal") %>%
group_by(Date, Plot) %>%
  mutate(Variable = "Flowering", 
         Percent=(Percent)) %>%
           ungroup()
         
```


##check data 

```{r}
# check
 
str(df_flower_simple)
```

Do the same to create the R7 (pollinated flower)

```{r}

# create df with flowering stages only (merged)
df_pollen <- df_flower %>%
  #mutate(Plot=Pot)%>%
filter(Variable == "Petal" | 
         Variable == "Bur1") %>%
group_by(Date, Plot) %>%
  mutate(Variable = "R7Pol", 
         Percent=(Percent)) %>%
           ungroup()




```





Do the same joining for Burr

```{r}

df_bur_simple <- df_flower %>%
filter(Variable == "Bur3" | 
         Variable == "Bur4"  ) %>%
group_by(Date, Plot) %>%
  mutate(Variable = "Bur", 
         Percent=(Percent))%>%
  ungroup()

```



Then create a class that is bud only 

```{r}
df_bud_simple <- df_flower %>%
  filter(Variable == "Bud")
  
  
```

Combine all three dataframes 

```{r}



str(df_bud_simple)
str(df_flower_simple)
str(df_bur_simple)
str(df_pollen)


```

```{r}

# merge both dfs
df_bud_flow_bur_simple <- 
  rbind(df_bud_simple, df_flower_simple, df_pollen, df_bur_simple)
  #rbind(df_bud_simple, df_flower_simple)
#check
summary(df_bud_flow_bur_simple)

#Save as table 
write.table(df_bud_flow_bur_simple, "GCdf_bud_flow_bur_simple.txt")
```


#Graph of merged 

```{r graph,fig.height= 5,fig.width= 10, warning=FALSE}
# graph it
df_bud_flow_bur_simple %>%
  filter(Variable == "Bud" |
           Variable =="Flowering"| 
           Variable =="Bur")  %>%
  mutate(Variable = 
  factor(Variable,levels = c("Bud","Flowering",
                             "Bur"))) %>%
  group_by(DAS,Cultivar,Variable) %>%
  summarise_each(funs(mean)) %>%
  #select(Variable,Percent, Cultivar,DAS,SowTreat, TTAS) %>%
  #filter(SowTreat == "S1" | SowTreat == "S2" | SowTreat == "S3" | SowTreat == "S4" ) %>%
  #filter(Cultivar == "Monti" | Cultivar == "Leura") %>%
  filter(Variable == "Bud")%>%
 #ggplot(aes(x=DAS, y=Percent)) + 
  ggplot(aes(x=TTAS, y=Percent)) + 
  geom_line(aes(colour=Cultivar)) +
  geom_point(aes(shape=Cultivar,colour=Cultivar))+
  facet_grid(Cultivar~., scales = "free") +
  #facet_grid(SowTreat~Cultivar, scales = "free") +
  geom_abline(intercept = 50, slope = 0) +
  ylab("Percent of plants with floral Bud (%)") +
   xlab(expression(Thermal~time~~"("^"o"*"Cd)"))+
  #xlab("Thermal-time from sowing (oCd)")+
  theme_bw()+
theme(axis.text.x = element_text(angle = 60, hjust = 1))
```


```{r}
# graph it
df_bud_flow_bur_simple %>%
  filter(Variable == "Bud" |
           Variable =="Flowering"| 
           Variable =="Bur")  %>%
  mutate(Variable = 
  factor(Variable,levels = c("Bud","Flowering",
                             "Bur"))) %>%
  group_by(DAS,Cultivar,Variable) %>%
  summarise_each(funs(mean)) %>%
  #select(Variable,Percent, Cultivar,DAS,SowTreat, TTAS) %>%
  #filter(SowTreat == "S1" | SowTreat == "S2" | SowTreat == "S3" | SowTreat == "S4" ) %>%
  #filter(Cultivar == "Monti" | Cultivar == "Leura") %>%
   #filter(Cultivar == "Monti" ) %>%
 # filter (SowTreat == "S1") %>%
  filter(Variable == "Flowering" | Variable == "Bur")%>%
 #ggplot(aes(x=DAS, y=Percent)) + 
  ggplot(aes(x=TTAS, y=Percent)) + 
  geom_line(aes(colour=Cultivar)) +
  geom_point(aes(shape=Cultivar,colour=Cultivar))+
  facet_grid(.~Variable, scales = "free") +
  #facet_grid(SowTreat~Cultivar, scales = "free") +
  geom_abline(intercept = 50, slope = 0) +
  ylab("Percent of plants with floral Bud (%)") +
   xlab(expression(Thermal~time~~"("^"o"*"Cd)"))+
  #xlab("Thermal-time from sowing (oCd)")+
  theme_bw()+
theme(axis.text.x = element_text(angle = 60, hjust = 1))

```



