---
title: "WaterAct 6CV"
author: "CT"
date: "Thursday, February , 2016"
output: 
  word_document: default
  pdf_document: default
  html_document: default
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(markdown)
#install.packages(markdown)

```


```{r loadFile}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\WaterAct")
getwd()

#create file
df_seed <- read.table("WaterAct.txt",header=TRUE)

head(df_seed)
# Jeito 1 de trocar formato (usando base R)
#df_seed$Date <- dmy(df_seed$Date)

# change format  (with dplyr)
df_seed <- df_seed %>%
  mutate(Plot = as.factor(Plot), 
         Block = as.factor(Block),
         Cultivar = as.factor(Cultivar),
         SowTreat = as.factor(SowTreat))

summary(df_seed) # explore values
str(df_seed) # check formats
head(df_seed) # see to rows
tail(df_seed)

```



```{r}


#Graph it  
df_seed %>%
  ggplot(aes(x=SowTreat, y=WaterAct, colour=factor(Cultivar)))+
  geom_boxplot() +
  geom_jitter() +
  theme(axis.text.x=element_text(angle = +90, hjust = 0))+
  facet_grid(Depth~SowTreat)

```


```{r, fig.height=7, fig.width=15}
  df_seed %>%
   mutate (SowTreat= factor(SowTreat, levels=c("S1", "S2", "S3", "S4", "S6","S7"),labels=c("June", "July", "September", "November", "February","March")))%>%
  group_by(Cultivar,SowTreat, Depth) %>%
  dplyr::select(WaterAct)%>%
  summarise_all(funs(mean,sd)) %>%
  ggplot(aes(x=Cultivar, y=mean, colour=Cultivar,     shape=Cultivar)) +
  geom_point(size=5, alpha=0.8) +
  geom_line() +
 facet_grid(Depth~SowTreat) +
  labs(x="Cultivar",y="Water Activity (aw)") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_errorbar(aes(ymin=mean-sd/1.73,
                    ymax=mean+sd/1.73))+
  theme_bw()+
    ylim(0,1)+
 theme(axis.text.x=element_text(angle = 45, hjust = 1, size= 14))+
  theme(axis.text.y=element_text(angle = 0, hjust = 0, size= 14))+
   #remove grid lines 
   theme(
     panel.border = element_rect(colour = "black", size = 2), 
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank(),
     axis.line = element_line(colour = "black"))+
  theme(text = element_text(size=16))+
   
   
   #make TT target labels  white  
   theme(strip.background = element_rect(colour = "black", fill = "white",size=2))

ggsave("plots_WaterActSowingD.tiff", width=14, height=7, dpi=500)



```


 get the mean value of water activity 

```{r Graph}
df_seedmean <-df_seed %>%
  group_by(Cultivar,SowTreat) %>%
  dplyr::select(WaterAct)%>%
  summarise_all(funs(mean))


  
```
Then bring the hardseed data 

```{r}

setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\WaterAct")
getwd()
df_Hard <- read.table ("MaxHardness.txt",header=TRUE)

str(df_Hard)

df_H <-df_Hard %>%
  dplyr::select(Cultivar,SowTreat, Hard_perc)%>%
  group_by(Cultivar,SowTreat)%>%
  summarise_all(funs(mean,sd))
  
```

then merge the two data frames by cultivar sowtreat 


```{r}

df_HAW <- merge(df_H, df_seedmean, by=c("Cultivar","SowTreat"))

str(df_HAW)
```


Calculate the mean and error bars for each cultivar 

```{r, fig.height=5, fig.width=10}
df_HAW %>%
  mutate (SowTreat= factor(SowTreat, levels=c("S1", "S2", "S3", "S4", "S6","S7"),labels=c("June", "July", "September", "November", "February","March")))%>%
  ggplot(aes(x=WaterAct, y=mean, colour=Cultivar, shape=SowTreat)) +
  geom_point(size=4, alpha=0.8) +
 # geom_line() +
  #facet_grid(.~SowTreat) +
  labs(x="Water Activity (aw) ",y="Maximum percentage of hardseeds (%) ") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_errorbar(aes(ymin=mean-sd/1.73,
                    ymax=mean+sd/1.73))+
  ylim(0,100)+
  xlim(0,0.8)+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 0, hjust = 0.5, size = 14))+
  theme(axis.title.x = element_text(angle = 0, hjust = 0.5, size = 16))+
  theme(axis.text.y = element_text(angle = 0, hjust = 1, size = 14))+
theme(axis.title.y = element_text(angle = 90, hjust = 0.5, size = 16))





```


```{r}


write.table (df_HAW, "df_HAW.txt"  )
#markdown::render("<C:\\GitHubRepos\\SubCloverPhD\\SubClover\\HardseedsProject1Read.Rmd>") 
```


ANOVAfor water activity 

```{r}

str(df_seed)

file <- df_seed %>%
  dplyr::select(Block, Cultivar,SowTreat,Plot,Depth,WaterAct,MoistureEstimate)
 

#-------------------------------------------------

# Chosen transform log to do anova 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
#my.anova <- aov(SoftGerm_perc~ Cultivar*SowTreat + Block, data = file.subset)
my.anova <- aov(MoistureEstimate~ SowTreat*Cultivar + Depth, data = file.subset)
#my.anova <- aov(WaterAct~ Depth + Block, data = file.subset)
#my.anova <- aov(WaterAct~ SowTreat*Cultivar + Block, data = file.subset)
```


```{r}
summary(my.anova)
#TukeyHSD(my.anova)
```


```{r}
#Means separation 
#(LSD.test(my.anova, c("Cultivar","SowTreat"), alpha= 0.05, p.adj="none"))
(LSD.test(my.anova, c("SowTreat"), alpha= 0.05, p.adj="none"))
 #(LSD.test(my.anova, c("Depth"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none"))
```


s1


ANOVAfor water activity 

```{r}
file <- df_seed %>%
  dplyr::select(Block, Cultivar,SowTreat,Plot,Depth,WaterAct) %>%
  filter(SowTreat=="S1")
 

#-------------------------------------------------

# Chosen transform log to do anova 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(WaterAct~ Cultivar*Depth + Block, data = file.subset)
#my.anova <- aov(WaterAct~ Cultivar + Block, data = file.subset)
#my.anova <- aov(WaterAct~ Depth + Block, data = file.subset)
#my.anova <- aov(WaterAct~ SowTreat + Block, data = file.subset)
```


```{r}
summary(my.anova)
#TukeyHSD(my.anova)
```


```{r}
#Means separation 
#(LSD.test(my.anova, c("Cultivar","SowTreat"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("SowTreat"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("Depth"), alpha= 0.05, p.adj="none"))
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none"))
```



S2 ANOVAfor water activity 

```{r}
file <- df_seed %>%
  dplyr::select(Block, Cultivar,SowTreat,Plot,Depth,WaterAct) %>%
  filter(SowTreat=="S2")
 

#-------------------------------------------------

# Chosen transform log to do anova 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(WaterAct~ Cultivar*Depth + Block, data = file.subset)
#my.anova <- aov(WaterAct~ Cultivar + Block, data = file.subset)
#my.anova <- aov(WaterAct~ Depth + Block, data = file.subset)
#my.anova <- aov(WaterAct~ SowTreat + Block, data = file.subset)
```


```{r}
summary(my.anova)
#TukeyHSD(my.anova)
```


```{r}
#Means separation 
#(LSD.test(my.anova, c("Cultivar","SowTreat"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("SowTreat"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("Depth"), alpha= 0.05, p.adj="none"))
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none"))
```

S3


ANOVAfor water activity 

```{r}
file <- df_seed %>%
  dplyr::select(Block, Cultivar,SowTreat,Plot,Depth,WaterAct) %>%
  filter(SowTreat=="S3")
 

#-------------------------------------------------

# Chosen transform log to do anova 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(WaterAct~ Cultivar*Depth + Block, data = file.subset)
#my.anova <- aov(WaterAct~ Cultivar + Block, data = file.subset)
#my.anova <- aov(WaterAct~ Depth + Block, data = file.subset)
#my.anova <- aov(WaterAct~ SowTreat + Block, data = file.subset)
```


```{r}
summary(my.anova)
#TukeyHSD(my.anova)
```


```{r}
#Means separation 
#(LSD.test(my.anova, c("Cultivar","SowTreat"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("SowTreat"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("Depth"), alpha= 0.05, p.adj="none"))
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none"))
```


S4
ANOVAfor water activity 

```{r}
file <- df_seed %>%
  dplyr::select(Block, Cultivar,SowTreat,Plot,Depth,WaterAct) %>%
  filter(SowTreat=="S4")
 

#-------------------------------------------------

# Chosen transform log to do anova 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(WaterAct~ Cultivar*Depth + Block, data = file.subset)
#my.anova <- aov(WaterAct~ Cultivar + Block, data = file.subset)
#my.anova <- aov(WaterAct~ Depth + Block, data = file.subset)
#my.anova <- aov(WaterAct~ SowTreat + Block, data = file.subset)
```


```{r}
summary(my.anova)
#TukeyHSD(my.anova)
```


```{r}
#Means separation 
#(LSD.test(my.anova, c("Cultivar","SowTreat"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("SowTreat"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("Depth"), alpha= 0.05, p.adj="none"))
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none"))
```

s6


ANOVAfor water activity 

```{r}
file <- df_seed %>%
  dplyr::select(Block, Cultivar,SowTreat,Plot,Depth,WaterAct) %>%
  filter(SowTreat=="S6")
 

#-------------------------------------------------

# Chosen transform log to do anova 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(WaterAct~ Cultivar*Depth + Block, data = file.subset)
#my.anova <- aov(WaterAct~ Cultivar + Block, data = file.subset)
#my.anova <- aov(WaterAct~ Depth + Block, data = file.subset)
#my.anova <- aov(WaterAct~ SowTreat + Block, data = file.subset)
```


```{r}
summary(my.anova)
#TukeyHSD(my.anova)
```


```{r}
#Means separation 
#(LSD.test(my.anova, c("Cultivar","SowTreat"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("SowTreat"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("Depth"), alpha= 0.05, p.adj="none"))
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none"))
```

s7

ANOVAfor water activity 

```{r}
file <- df_seed %>%
  dplyr::select(Block, Cultivar,SowTreat,Plot,Depth,WaterAct) %>%
  filter(SowTreat=="S7")
 

#-------------------------------------------------

# Chosen transform log to do anova 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
#my.anova <- aov(WaterAct~ Cultivar*Deptht + Block, data = file.subset)
my.anova <- aov(WaterAct~ Cultivar + Block, data = file.subset)
#my.anova <- aov(WaterAct~ Depth + Block, data = file.subset)
#my.anova <- aov(WaterAct~ SowTreat + Block, data = file.subset)
```


```{r}
summary(my.anova)
#TukeyHSD(my.anova)
```


```{r}
#Means separation 
#(LSD.test(my.anova, c("Cultivar","SowTreat"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("SowTreat"), alpha= 0.05, p.adj="none"))
#(LSD.test(my.anova, c("Depth"), alpha= 0.05, p.adj="none"))
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none"))
```










