---
title: "Harvest time of the  6CV Iversen 2"
author: "CT"
date: " 07.06.2016"
output: html_document
---
Purpose of this script : 
calculate the days to harvest from Iversen 2 dataset 

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)

```

Read the file and check formats 

```{r loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover\\HarvestDASIv2")
getwd()

#create file
df_Hvst <- read.table("DAStoHarvest.txt",header=TRUE)
head(df_Hvst)


# define formats 
df_Hvst$HarvestDate <- dmy(df_Hvst$HarvestDate )
df_Hvst$SowingD <- dmy(df_Hvst$SowingD)
df_Hvst$SowTreat <- as.factor(df_Hvst$SowTreat)
df_Hvst$Block <- as.factor(df_Hvst$Block)
df_Hvst$Plot <- as.factor(df_Hvst$Plot)
    

str(df_Hvst)
# head(df_Hvst)
# summary(df_Hvst)
# tail(df_Hvst)



```


Graph and check data 


```{r , fig.height=5, fig.width= 10}

df_Hvst %>%
group_by(Cultivar, SowingD, SowTreat) %>%
  dplyr::select(DAS, SowTreat) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=SowTreat, y=(mean))) +
  geom_point(aes(colour=Cultivar), size=6) +
  geom_line(aes(colour=Cultivar)) +
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2), width=0.2)   +
  theme_grey(base_size = 20) +
  theme_bw()+
  theme(text = element_text(size = 24))+
  #facet_grid(Cultivar~., scales="free") +
    labs(y= "Days to harvest ")+
  ylim(150,350)





```

filter specific dates for each harvest 

```{r}



```



Here overall anova for sowTreat and cultivar (overview here; individual SowTreat analysis in script 2 )
```{r ANOVA}

shapiro.test(df_Hvst$DAS)

my.anova <- aov(DAS ~ Cultivar*SowTreat + Block, data = df_Hvst)
summary(my.anova)
TukeyHSD(my.anova)




```

```{r}
#Means separation 
#(LSD.test(my.anova, c("Cultivar","SowTreat"), alpha= 0.05, p.adj="none")) 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none")) 

```

End of this script. Continue in script Harvest Project2 





