---
title: "Hardseeds GC Max"
author: "CT"
date: " 22 November , 2016"
output: pdf_document
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)


```


```{r loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\Gitsubclover\\GCBurrSeed")
getwd()

#create file
df_seed <- read.table("HardseedGC.txt",header=TRUE)
head(df_seed)
summary(df_seed)

# change date format   ( basic R)
#df_seed$Date <- dmy(df_seed$Date)


```

```{r}
# format change ( dplyr)
df_seed <- df_seed %>%
  mutate(Cultivar = as.factor(Cultivar), FlowerStage = as.factor(FlowerStage))%>%
  mutate(Round = as.numeric(Round),
         NumberSeeds = as.numeric(NumberSeeds),
         Soft = as.numeric (Soft),
         DaysTest = as.numeric(DaysTest))
  

summary(df_seed) # explore values
str(df_seed) # check formats
head(df_seed) # see to rows
tail(df_seed)
```



```{r CreatePercentSoft}

df_seed <- df_seed %>%
#  mutate(Soft = as.numeric(Soft)) %>%
  mutate(PropSoft = round(Soft/(NumberSeeds)*100,digits=2))

df_hardmax <- df_seed %>%
  group_by(Rep,FlowerStage) %>% 
  dplyr::select(-DaysTest) %>%  
  arrange(Round) %>% # need to tell which factor to accumulate within
  mutate(CumPropSoft = cumsum(PropSoft)) 
  

summary (df_hardmax)



```


```{r}

#Need to calculate Proportion of Hardseeds (0-1) under construction
df_hardmax %>%
  mutate(hardSeed = 100-CumPropSoft) %>%
    #filter(Round == 1) %>%  #need to keep filter to get first and max hardseed percent
  #mutate(FlowerStage = factor(Depth,levels=c( "young","old"))) %>%
  group_by(Cultivar,Round,FlowerStage) %>%
  dplyr::select(hardSeed) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=Round, y=mean, colour=factor(Cultivar), shape=factor(Cultivar))) +
  geom_point() +
  geom_boxplot() +
 facet_grid(.~FlowerStage) +
  labs(x="Round",y="Maximum Percentage of Hardseeds") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2))+
  theme_bw()+
  ylim(0,100)



```


Stoped here!!


```{r}

#Graph the maximum percentage of Live hardseeds!!! 

  df_hardmax %>%
  filter(Round == 1) %>%
  group_by(Cultivar,Round, FlowerStage) %>%
  dplyr::select(CumSoft) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=SowingD, y=mean, colour=factor(Cultivar), shape=factor(Cultivar))) +
  geom_point() +
  geom_line() +
 facet_grid(Depth~Cultivar) +
  labs(x="Sowing Date",y="Maximum Percentage of LiveHardseeds") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2))+
  ylim(0,100)








```




```{r}

  
#Now need to correct the hardseed breakdown for the number of living seeds : use softLive and Total live

  
  
df_soft_live <- df_hard_live_max  %>%
  #dplyr::select(-Date) %>%
  group_by(SowTreat,Cultivar,Depth, Plot) %>% # need to keep level in which cumulation occurs
  arrange(Round) %>% # need to tell which factor to accumulate within
  mutate(CumSoft_live = cumsum(Soft_live)) %>%
 mutate(HardLive_perc = round(100-(CumSoft_live/Total_live*100),2))

head (df_soft_live)
  summary (df_soft_live)


#Graph Breakdown Living hard seeds 

df_soft_live %>%
  mutate(SowingD = dmy(SowingD)) %>%
  #filter(Round == 1) %>%
  group_by(Cultivar,SowingD, SowTreat, Depth, Round) %>%
  dplyr::select(HardLive_perc) %>%
  summarise_each(funs(mean)) %>%
  ggplot(aes(x=Round, y=mean, colour=factor(Cultivar), shape=factor(Cultivar))) +
  geom_point() +
  geom_line() +
  ylim(0,100)+
 facet_grid(.~Depth) +
  labs(x="Round",y="Percentage of LiveHardseeds") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

#Calculate slopes not working 

plots <- unique(df_soft_plot$Plot)
depth <- unique(df_soft_plot$Depth)
all.data <- NULL
for(p in 1:length(plots)) {
  for(d in 1:length(depth)) {
  
  df_sub <- subset(df_soft_plot, (df_soft_plot$Plot==plots[p] & Depth == depth[d]))
  
  x <- df_sub$Round
  y <- 1-df_sub$PercSoftCum
  
  print(data.frame(x=x,y=y))
  
  
  fit <- NULL
  fit <- lm(y ~ x)
  
  intercept <- round(fit$coefficients[[1]],2)
  slope <- round(fit$coefficients[[2]],3)
  r2 <- round(summary(fit)$r.squared * 100,2)
  # summary(fit)$adj.r.squared
  block <- df_sub$Block[1]
  cv <- as.character(df_sub$Cultivar[1])
  sow <- as.character(df_sub$SowTreat[1])
  sd <- dmy(df_sub$SowingD[1])
  
  
  buf <- c(sow,cv,block, plots[p],  depth[d], intercept, slope, r2, nrow(df_sub))
  print(buf)
  
    if (p==1 & d==1) {
    all.data <- data.frame(
    sow = sow,
    cv = cv,
    block = block, 
    plot = plots[p],  
    depth = depth[d], 
    int = intercept, 
    slope = slope, 
    r2 = r2,
   n= nrow(df_sub)
    ) } else{
    all.data <- rbind(all.data, buf)
  }
  
  

  }
  
}

summary(all.data)

```


Graph date Propsoft  

```{r Graph}



df_seed %>%
  select(SowTreat, Date,Block, Cultivar,PropSoft) %>%
  ggplot (aes(x=SowTreat,y=PropSoft)) +
  geom_point(aes(colour = Block)) +
  facet_grid(Block ~ Cultivar)
  
#Graph seedsoft for S1, rounds 1 2 and 3
head(df_seed)
  df_seed %>%
  select(SowTreat, Date,Block, Cultivar,Round, PropSoft)%>%
  ggplot (aes(x=Round,y=PropSoft)) +
  geom_point(aes(colour = SowTreat)) +
  facet_grid(Block ~ Cultivar)
  
  
```


```{r}
#Sum up the PropSoft starting form Round 1 (minimum soft) then round 2 and 3 
#Fix here 

head(df_seed)
  df_seed %>%c
  mutate(SumPropSoft = cumsum(PropSoft))
  
```




Calculate the mean and error bars for each cultivar 

```{r}
df_seed %>%
  mutate(hardSeed = 100-PropSoft) %>%
  mutate(SowingD = dmy(SowingD)) %>%
  #filter(Round == 1) %>%
  group_by(Cultivar,SowingD) %>%
  dplyr::select(hardSeed) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=SowingD, y=mean, colour=factor(Cultivar), shape=factor(Cultivar))) +
  geom_point() +
  geom_line() +
 facet_grid(.~Cultivar) +
  labs(x="Sowing Date",y="Maximum Percentage of Hardseeds") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2))+
  ylim(0,100)

head(df_seed)

df_seedANOVA <- df_seed %>%
mutate(hardSeed = 100-PropSoft) %>%
filter(Round == 1) 

head(df_seedANOVA)



#ANOVA

#data transformation
df_seedANOVA$transf_no <- 1*(df_seedANOVA$hardSeed)
df_seedANOVA$transf_sqr <- sqrt(df_seedANOVA$hardSeed)
df_seedANOVA$transf_log <- log(df_seedANOVA$hardSeed)
df_seedANOVA$transf_acos <- acos(df_seedANOVA$hardSeed/100)
df_seedANOVA$transf_power3 <- (df_seedANOVA$hardSeed)^3




write.table(df_seedANOVA,"df_seedANOVA.txt")
file <- df_seedANOVA

x <- c( "transf_no",  "transf_sqr", "transf_log", "transf_acos", "transf_power3")

colsSelec <- match(x,colnames(file))

file %>%
  tidyr::gather("transformation" ,"value",colsSelec) %>%
  ggplot(aes(value)) + 
  geom_histogram() +
  facet_grid(.~transformation, scales="free" )

head(file)
head(df_seedANOVA)
#normality test
#tranform log was the best histogram so continue with it 
shapiro.test(file$transf_acos)

#QQplot
var<-file$transf_acos
qqnorm(var)
qqline(var, col = 2)
qqplot(var, rt(300))

#-------------------------------------------------

# Chosen transform log to do anova 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_acos ~ Cultivar*SowTreat + Block, data = file.subset)

summary(my.anova)
TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar","SowTreat"), alpha= 0.05, p.adj="none")) 


```


```{r}

markdown::render("<C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\Gitsubclover\\HardseedsProject1Read.Rmd>") 
```


