---
title: "Hardseeds Slopes 6CV"
author: "CT"
date: "Tuesday, July 19, 2016"
output:
  word_document: default
  pdf_document: default
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(markdown)

```


```{r loadFile}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\Hardseeds")
getwd()

#create file
df_seed <- read.table("dfHard_break.txt",header=TRUE)

head(df_seed)




```

Just change name of dataframe
```{r}
#Select depth of interest start with above seeds 

dfSubSet<- df_seed%>%
  #filter (Depth== "Above")
 dplyr::select(Plot, Cultivar, Block, SowingD, SowTreat, Depth, Round, HardAccum)
  
```



```{r}
all.data<-data.frame()
counter<-0
plots<-unique(dfSubSet$Plot)
depth<-unique(dfSubSet$Depth)

length(plots)*length(depth)
#p=d=1
for(p in 1:length(plots)) {
  for(d in 1:length(depth)) {
  df_sub <- data.frame()  
   # print(paste0(plots[p],"_",depth[d]))
  #  counter<-counter+1
    
  df_sub <- dfSubSet %>% filter(Plot==plots[p] & Depth == depth[d])
  
  
  # Linear fit
  x <- df_sub$Round
  y <- df_sub$HardAccum
  
  #print(data.frame(x=x,y=y))
  
  fit <- NULL
  fit <- lm(y ~ x)
  
  intercept <- round(fit$coefficients[[1]],2)
  slope <- round(fit$coefficients[[2]],3)
  r2 <- round(summary(fit)$r.squared * 100,2)
  # summary(fit)$adj.r.squared
  cv <- as.character(df_sub$Cultivar[1])
  block <- as.character(df_sub$Block[1])
  sow <- as.character(df_sub$SowTreat[1])
  sd <- dmy(df_sub$SowingD[1])
  
  
  buf <- data.frame(sow=sow,cv=cv, block=block, plot=plots[p],depth=depth[d], int=intercept, slope=slope, r2=r2, n=nrow(df_sub))
  
  all.data <- rbind(buf, all.data)
  
 # print(buf)
  
  #print(nrow(df_sub))
    
  #subset(dfSubSet, (dfSubSet$Plot==plots[p] & Depth == depth[d]))
    
  }
  
}

summary(all.data)

```
write
```{r}
write.table(all.data, "df_slopesBreak.txt")
```



