---
title: "Hardseeds Live Max 6CV"
author: "CT"
date: "22.09.2016"
output:
  word_document: default
  pdf_document: default
---


```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)


```

This script reads the df_slopesBreak.txt produced in script number 4 and run anova in the slopes as indicator of hardseedbreakdown 

```{r loadFile}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\Hardseeds")
getwd()

#create file
df_seed <- read.table("df_slopesBreak.txt",header=TRUE) 

str(df_seed)
```

## Create index to filter for loop ANOVA

```{r}
y <- c("S1","S2","S3","S4","S6","S7")

sdIndex <- unique(df_seed$sow)

sdIndex[order(match(sdIndex,y))]

length(sdIndex)
sdIndex
```


```{r}
for (i in 1:length(sdIndex)) {
  
 #print(i)
 print(paste0(sdIndex[i],"--------------------------------"))
  
  file.subset <- df_seed %>%
  filter(sow==sdIndex[i])

  head(file.subset, 50)
   summary(file.subset)
my.anova <- aov(slope~ cv*depth + block, data = file.subset)
print(summary(my.anova))

if ((summary(my.anova)[[1]][["Pr(>F)"]][1])<0.05) {
  print("***Sig CV***") 
  print((LSD.test(my.anova, c("cv"), alpha= 0.05, p.adj="none"))) } # do if

if ((summary(my.anova)[[1]][["Pr(>F)"]][2])<0.05) {print("***Sig Depth***")
  print((LSD.test(my.anova, c("depth"), alpha= 0.05, p.adj="none")))
  } 
if ((summary(my.anova)[[1]][["Pr(>F)"]][3])<0.05) {print("***Sig Block***")
  print((LSD.test(my.anova, c("block"), alpha= 0.05, p.adj="none")))
  } 
if ((summary(my.anova)[[1]][["Pr(>F)"]][4])<0.05) {print("***Sig CV:Depth Int***")
  print((LSD.test(my.anova, c("cv:depth"), alpha= 0.05, p.adj="none")))
  } 

# make mean separation if seignificant

(LSD.test(my.anova, c("cv"), alpha= 0.05, p.adj="none"))
  
}
```


```{r}

```











