---
title: "Hardseeds 6CV Follow up Stats; logit transformed data from maximum (total )hardseeds (round 1)  "
author: "CT"
date: "Thursday, FEbruary 3, 2016"
output:
  word_document: default
  pdf_document: default
  
  This script does,
  reads the table generated in 
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(rgr)
```


```{r loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\Gitsubclover\\Hardseeds")
getwd()

#create file dftablehardseeds1 is created in HardseedsProject1 script

df_seedH <- read.table("dftablehardseeds1.txt",header=TRUE)
head(df_seedH)
summary(df_seedH)


```



 Here suggestion first suggestion of Dean transform (2016!)

```{r}

#ANOVA

#data transformation many possibilities but logit worked well 
df_seedH$transf_no <- 1*(df_seedH$hardSeed)
# df_seedH$transf_sqr <- sqrt(df_seedH$hardSeed)
# df_seedH$transf_log <- log(df_seedH$hardSeed)
# df_seedH$transf_acos <- acos(df_seedH$hardSeed/100)
# df_seedH$transf_power3 <- (df_seedH$hardSeed)^3
#df_seedH$transf_logit <- logit(df_seedH$hardSeed/100)

write.table(df_seedH,"df_seedHanova.txt")
file <- df_seedH

#x <- c( "transf_no",  "transf_sqr", "transf_log", "transf_acos", "transf_power3")
x <- c( "transf_no",  "transf_logit")
colsSelec <- match(x,colnames(file))

file %>%
  tidyr::gather("transformation" ,"value",colsSelec) %>%
  ggplot(aes(value)) + 
  geom_histogram() +
  facet_grid(.~transformation, scales="free" )

head(file)
head(df_seedH)
#normality test
#tranform log was the best histogram so continue with it 
shapiro.test(file$transf_no)

#QQplot
# var<-file$transf_logit
# qqnorm(var, ylim = 1)
# qqline(var, col = 2)
# qqplot(var, rt(3000))

#-------------------------------------------------

# Chosen transform log to do anova 
file.subset <- file 

head(file.subset)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar*SowingD + Block, data = file.subset)

summary(my.anova)
TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar","SowingD"), alpha= 0.05, p.adj="none")) 


```

Here ANOVA according S. Saville advice : LSD test unprotected by sowing date 

```{r}
#Filter  S1, S2, S3, S6 , S7 
summary(df_seedH)

df_seedHS6 <- df_seedH %>%
  #filter(SowingD=="2015-06-24")
  #filter(SowingD=="2015-07-28")
  #filter(SowingD=="2015-09-15")
  filter(SowingD=="2015-11-05")
  #filter(SowingD=="2016-02-17")
  #filter(SowingD=="2016-03-15")

#data transformation many possibilities but logit worked well, however little difference between real and transformed numbers 

#-------------------------------------------------
# anova 
file <- df_seedHS6


file.subset <- file 

head(file.subset)
summary(file.subset)


```

```{r}
#ANOVA
my.anova <- aov(hardSeed ~ Cultivar + Block, data = file.subset)

summary(my.anova)
```

Then use multiple comparisons of means
```{r}
#Means separation after ANOVA
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none")) 
```


