---
title: "Hardseeds Slopes 6CV"
author: "CT"
date: "Tuesday, July 19, 2016"
output: pdf_document
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(markdown)
#install.packages(markdown)

```


```{r loadFile}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover")
getwd()

#create file
df_seed <- read.table("HardseedSlope.txt",header=TRUE)
head(df_seed)


# jeito 2 de trocar formato (usando dplyr)
df_seed <- df_seed %>%
  mutate(cv = as.factor (cv), plot = as.factor(plot), block = as.factor(block))

summary(df_seed) # explore values
str(df_seed) # check formats
head(df_seed) # see to rows
tail(df_seed)

```

Run anova slopes 

```{r}

my.anova <- aov(slope ~ cv*depth + block, data = df_seed)

summary(my.anova)
TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("cv","depth"), alpha= 0.05, p.adj="none"))



```


```{r}





```


Graph date Propsoft  

```{r Graph}



  
  
```


```{r}

  
```




Calculate the mean and error bars for each cultivar 

```{r}




#ANOVA

#data transformation





write.table(df_seedANOVA,"df_seedANOVA.txt")
file <- df_seedANOVA

x <- c( "transf_no",  "transf_sqr", "transf_log", "transf_acos", "transf_power3")

colsSelec <- match(x,colnames(file))

file %>%
  tidyr::gather("transformation" ,"value",colsSelec) %>%
  ggplot(aes(value)) + 
  geom_histogram() +
  facet_grid(.~transformation, scales="free" )

head(file)
head(df_seedANOVA)
#normality test
#tranform log was the best histogram so continue with it 
shapiro.test(file$transf_acos)

#QQplot
var<-file$transf_acos
qqnorm(var)
qqline(var, col = 2)
qqplot(var, rt(300))

#-------------------------------------------------

# Chosen transform log to do anova 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_acos ~ Cultivar*SowTreat + Block, data = file.subset)

summary(my.anova)
TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar","SowTreat"), alpha= 0.05, p.adj="none")) 


```


```{r}

markdown::render("<C:\\GitHubRepos\\SubCloverPhD\\SubClover\\HardseedsProject1Read.Rmd>") 
```


