---
title: "Hardseeds Total Max 6CV"
author: "CT"
date: "Thursday, 22 September , 2015"
output: pdf_document
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)


```


```{r loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\Gitsubclover\\Hardseeds")
getwd()

#create file
df_seed <- read.table("HardseedsData.txt",header=TRUE)
head(df_seed)
# change date format ( base R)
df_seed$Date <- dmy(df_seed$Date)

# change formats with dplyr
df_seed <- df_seed %>%
  mutate(Plot = as.factor(Plot), Block = as.factor(Block)) %>%
#  mutate(Soft = as.numeric(Soft)) %>%
  mutate(PropSoft = round(Soft/max(SeedNumber)*100,digits=2))

summary(df_seed) # explore values
str(df_seed) # check formats
head(df_seed) # see to rows
tail(df_seed)

df_seed %>%
  filter(Plot==1)


```




Graph the potential Hardseededness 
good ref font size control :http://stackoverflow.com/questions/25061822/ggplot-geom-text-font-size-control


```{r, fig.height=5, fig.width=10}

df_seed %>%
  mutate(hardSeed = 100-PropSoft) %>%
  mutate(SowingD = dmy(SowingD)) %>%
    filter(Round == 14) %>%  #need to keep filter to get first and max hardseed percen
  mutate(Depth = factor(Depth,levels=c( "Above","Below"))) %>%
  group_by(Cultivar,SowingD,Depth) %>%
  #cultivars filtered for power point 
  filter(Cultivar == "Antas"| Cultivar == "Monti") %>%
  dplyr::select(hardSeed) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=SowingD, y=mean, colour=factor(Cultivar), shape=factor(Cultivar))) +
  geom_point() +
  geom_line() +
 facet_grid(.~Depth) +
  labs(x="Sowing Date",y="Maximum Percentage of Hardseeds") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2))+
  theme_bw()+
  ylim(0,100)

head(df_seed)

summary(df_seed)



```



```{r fig.height=5, fig.width=10}


df_seed %>%
  mutate(hardSeed = 100-PropSoft) %>%
  mutate(SowingD = dmy(SowingD)) %>%
    filter(Round == 14) %>%  #need to keep filter to get first and max hardseed percen
  mutate(Depth = factor(Depth,levels=c( "Above","Below"))) %>%
  group_by(Depth, SowingD, Cultivar) %>%
  #cultivars filtered for power point 
  #filter(Cultivar == "Antas"| Cultivar == "Monti") %>%
  dplyr::select(hardSeed) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=SowingD, y=mean, colour=factor(Cultivar), shape=factor(Cultivar))) +
  #ggplot(aes(x=Depth, y=mean)) +
  geom_line() +
  geom_point()+
 #facet_grid(.~Depth) +
  labs(x="Sowing Date",y="Maximum Percentage of Hardseeds") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_x_date(date_breaks = "1 month",date_labels =  "%b")+
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2))+
  theme_bw()+
   ylim(0,100)

head(df_seed)

summary(df_seed)


```





```{r, warning=FALSE}




g1 <- df_seed %>%
  dplyr::select(-Date) %>% #
  group_by(SowTreat,Cultivar,Depth, Plot) %>% # need to keep level in which cumulation occurs
  arrange(Round) %>% # need to tell which factor to accumulate within
  mutate(Soft_cum = cumsum(Soft)) %>%
  mutate(PercSoftCum=Soft_cum/max(SeedNumber))%>%
  group_by(SowTreat,Cultivar,Depth, Round) %>%
  summarise_each(funs(mean)) 



```



```{r, fig.height=4, fig.width=10}

head(df_seed)
  df_seed %>%
  mutate(SumPropSoft = cumsum(PropSoft))
  
  
  
  df_seed %>%
  mutate(hardSeed = 100-PropSoft) %>%
  mutate(SowingD = dmy(SowingD)) %>%
    filter(Round == 14) %>%  #need to keep filter to get first and max hardseed percent
  #mutate(Depth = factor(Depth,levels=c( "Above","Below"))) %>%
  group_by(Cultivar,SowingD,Depth) %>%
  dplyr::select(hardSeed) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=SowingD, y=mean, colour=factor(Cultivar), shape=factor(Cultivar))) +
  geom_point() +
  geom_line() +
 facet_grid(. ~ Cultivar) +
  labs(x="Sowing Date",y="Maximum Percentage of Hardseeds") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2))+
  theme_bw()+
  ylim(0,100)



```



here looking cultivars individually 

```{r, fig.height=5, fig.width=10}


head(df_seed)
  df_seed %>%
  mutate(SumPropSoft = cumsum(PropSoft))
  
  
  
  df_seed %>%
  mutate(hardSeed = 100-PropSoft) %>%
  mutate(SowingD = dmy(SowingD)) %>%
    filter(Round == 14) %>%  #need to keep filter to get first and max hardseed percent
  mutate(Depth = factor(Depth,levels=c( "Above","Below"))) %>%
  group_by(Cultivar,SowingD,Depth) %>%
  dplyr::select(hardSeed) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=SowingD, y=mean, colour=factor(Cultivar), shape=factor(Cultivar))) +
  geom_point() +
  geom_line() +
 facet_grid(Depth ~ Cultivar) +
  labs(x="Sowing Date",y="Maximum Percentage of Hardseeds") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2))+
  theme_bw()+
  ylim(0,100)

#head(df_seed)

#summary(df_seed)

```






```{r, r, fig.height=4, fig.width=10}

  # Create percent soft seeds 

g1 <- df_seed %>%
  dplyr::select(-Date) %>% #
  group_by(SowTreat,Cultivar,Depth, Plot) %>% # need to keep level in which cumulation occurs
  arrange(Round) %>% # need to tell which factor to accumulate within
  mutate(Soft_cum = cumsum(Soft)) %>%
  mutate(PercSoftCum=Soft_cum/max(SeedNumber))%>%
  group_by(SowTreat,Cultivar,Depth, Round) %>%
  summarise_each(funs(mean)) 

# per round
g1 %>%
  ungroup() %>%
mutate(Depth = factor(Depth,levels=c( "Above","Below"))) %>%
 filter(Cultivar == "Antas"| Cultivar == "Monti") %>%
ggplot(aes(x=Round, y=100*(1-PercSoftCum), colour=Cultivar, shape=Cultivar)) +
  geom_point() +
  geom_line() +
  facet_grid(Depth~SowTreat) +
  theme_bw()+
  # changes axis labels
  theme(axis.text = element_text(size = 8))+ 
  geom_vline(xintercept = 98, linetype=2)+
   labs(x="Days ",y="Cumulative Proportion Hardseeds")





```


 

```{r}


summary(g1)
#xy up down comparison
g1 %>%
  dplyr::select(Plot,PercSoftCum,Depth,Round) %>%
  tidyr::spread(Depth, PercSoftCum) %>%
  ggplot(aes(x=Below,y=Above))+
  geom_point(aes(colour=factor(Cultivar))) +
  stat_smooth(method = "lm") +
  facet_grid(SowTreat~.)

  
  
```


```{r}

df_soft_plot <- df_seed %>%
  dplyr::select(-Date) %>%
  group_by(SowTreat,Cultivar,Depth, Plot) %>% # need to keep level in which cumulation occurs
  arrange(Round) %>% # need to tell which factor to accumulate within
  mutate(Soft_cum = cumsum(Soft)) %>%
  mutate(PercSoftCum=Soft_cum/max(SeedNumber))

summary(df_soft_plot)
str(df_soft_plot)

plots <- unique(df_soft_plot$Plot)
depth <- unique(df_soft_plot$Depth)
all.data <- NULL

for(p in 1:length(plots)) {
  for(d in 1:length(depth)) {
  
  df_sub <- subset(df_soft_plot, (df_soft_plot$Plot==plots[p] & Depth == depth[d]))
  
  x <- df_sub$Round
  y <- 1-df_sub$PercSoftCum
  
  print(data.frame(x=x,y=y))
  
  
  fit <- NULL
  fit <- lm(y ~ x)
  
  intercept <- round(fit$coefficients[[1]],2)
  slope <- round(fit$coefficients[[2]],3)
  r2 <- round(summary(fit)$r.squared * 100,2)
  # summary(fit)$adj.r.squared
  block <- df_sub$Block[1]
  cv <- as.character(df_sub$Cultivar[1])
  sow <- as.character(df_sub$SowTreat[1])
  sd <- dmy(df_sub$SowingD[1])
  
  
  buf <- c(sow,cv,block, plots[p],  depth[d], intercept, slope, r2, nrow(df_sub))
  print(buf)
  
    if (p==1 & d==1) { 
    all.data <- data.frame(
    Sow = sow,
    Cv = cv,
    Block = block, 
    Plot = plots[p],  
    Depth = depth[d], 
    Int = intercept, 
    Slope = slope, 
    R2 = r2,
    n = nrow(df_sub)
    ) } else {
    all.data <- rbind(all.data, buf) # FIXME: Logic is not working for df creation
  }

# Error:  
#   Warning message:
# In `[<-.factor`(`*tmp*`, ri, value = "2") :
#   invalid factor level, NA generated
  

  }
  
}

summary(all.data)




  
```



```{r}

#just get the means and stdv of Hardseeds for cultivars in 4 SowD

df_Hard <-df_seed %>%
  mutate(hardSeed = 100-PropSoft) %>%
  mutate(SowingD = dmy(SowingD)) %>%
  filter(Round == 14) %>%
  group_by(Cultivar,SowingD) %>%
  dplyr::select(hardSeed) %>%
  summarise_each(funs(mean,sd))
head(df_Hard)


```




Calculate the mean and error bars for each cultivar 


```{r}

#write a table with all data to do stats

dftable1 <- df_seed %>%
  mutate(hardSeed = 100-PropSoft) %>%
  mutate(SowingD = dmy(SowingD)) %>%
    filter(Round == 14) %>%  #need to keep filter to get first and max hardseed percent
  #mutate(Depth = factor(Depth,levels=c( "surface","buried"))) %>%
  group_by(Cultivar,SowingD, Block, Depth) %>%
  dplyr::select(hardSeed) 
  #summarise_each(funs(mean,sd)) 

summary (dftable1)
write.table(dftable1, "dftablehardseeds1.txt", row.names=FALSE)


```





```{r}

  