---
title: "Hardseeds Live Max 6CV"
author: "CT"
date: "Thursday, 22 September , 2016"
output: html_document
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(markdown)
#install.packages(markdown)

```


```{r loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\Gitsubclover\\Hardseeds")
getwd()

#create file
df_seed <- read.table("HardseedsLiveData.txt",header=TRUE)
head(df_seed)
# Jeito 1 de trocar formato (usando base R)
df_seed$Date <- dmy(df_seed$Date)

# jeito 2 de trocar formato (usando dplyr)
df_seed <- df_seed %>%
  mutate(Plot = as.factor(Plot), Block = as.factor(Block)) %>%
  mutate(Soft = as.numeric(Soft),
         #Depth = factor(Depth,levels("up","down")),
         SoftDead = as.numeric(SoftDead),
         SoftGerm = as.numeric (SoftGerm),
         SoftAbn = as.numeric (SoftAbn),
         SoftUngerm = as.numeric (SoftUngerm))
  

summary(df_seed) # explore values
str(df_seed) # check formats
head(df_seed) # see to rows
tail(df_seed)



```



```{r CreatePercentSoft}
#Create a column that is the Accumulated Dead this is to calculate the Maximum hardseeds live 


df_hard_live <- df_seed %>%
  group_by(Plot,Depth) %>% 
  dplyr::select(-Date) %>% # 
  arrange(Round) %>% # need to tell which factor to accumulate within
  mutate(CumSoftDead = cumsum(SoftDead)) %>%
  #subtract number of dead seeds to find living seeds 
  mutate(Total_live = InitialSeedlotR1Number-max(CumSoftDead)) %>%
   mutate(Soft_live = SoftGerm + SoftUngerm + SoftAbn) %>%
  #filter(Round==1) %>%
  mutate(Hard_perc = round(100-(Soft_live/Total_live*100),2))

  
summary (df_hard_live)

head(df_hard_live)
summary(df_hard_live) # explore values


```


```{r}

#Graph the maximum percentage of Live hardseeds!!! 

  df_hard_live %>%
  mutate(SowingD = dmy(SowingD)) %>%
  filter(Round == 1) %>%
  group_by(Cultivar,SowingD) %>%
  dplyr::select(Hard_perc) %>%
  summarise_each(funs(mean,sd)) %>%
  ggplot(aes(x=SowingD, y=mean, colour=factor(Cultivar), shape=factor(Cultivar))) +
  geom_point() +
  geom_line() +
 facet_grid(.~Cultivar) +
  labs(x="Sowing Date",y="Maximum Percentage of LiveHardseeds") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  geom_errorbar(aes(ymin=mean-sd/2,
                    ymax=mean+sd/2))+
  ylim(0,100)



```




```{r}

  
#Now need to correct the hardseed breakdown for the number of living seeds : use softLive and Total live

  
  
df_soft_live <- df_hard_live  %>%
  #dplyr::select(-Date) %>%
  group_by(SowTreat,Cultivar,Depth, Plot) %>% # need to keep level in which cumulation occurs
  arrange(Round) %>% # need to tell which factor to accumulate within
  mutate(CumSoft_live = cumsum(Soft_live)) %>%
 mutate(HardLive_perc = round(100-(CumSoft_live/Total_live*100),2))

head (df_soft_live)
  summary (df_soft_live)
  str(df_soft_live)


#Graph Breakdown Living hard seeds 

df_soft_live %>% 
  group_by(Cultivar, Depth, SowTreat, Round) %>%
  summarise(HardLive_perc=mean(HardLive_perc)) %>%
  ggplot(aes(x=Round, y=HardLive_perc, 
             colour=Cultivar, shape=Cultivar)) +
  geom_point() +
  geom_line() +
  facet_grid(SowTreat~Depth) +
  labs(y="Percentage of live Hardseeds")+
  geom_vline(xintercept = 5, linetype=2)
  
  
  

```

