---
title: "ReAnalysis Table"
author: "CT"
date: "Thursday, November 05, 2015"
output: html_document
note: Re analysis data compilation; Days, TT and Photop.
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)

```


```{r loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover\\ReAnalysis")
getwd()

#create file
df_Re <- read.table("ReAnalysisData.txt",header=TRUE)

head(df_Re)

summary(df_Re)

#change formats 

df_Re$SowingDate <-dmy(df_Re$SowingDate)
df_Re$StartFlowering <-dmy(df_Re$StartFlowering)
```

Graph Box Plot 

```{r GraphBoxPlot}


 df_Re %>%
   ggplot(aes(x=AuthorYear, y=TtFlowerAdjusted)) + 
    geom_boxplot() +
  geom_jitter(width=0.25) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))




 df_Re %>%
  ggplot(aes(x=PhotopAtTtTarget, y=TtFlowerAdjusted)) + 
  geom_point(aes(colour=AuthorYear)) 
  facet_wrap (~AuthorYea,ncol=10, scales = "free")
  #+
  #labs(y="Percentage plants with first Trifoliate",x="Days after sowing") +
    # facet_wrap(~AuthorYear, scales = "free")
  

```
Graph per ...


```{rGraphFacetwrap}



```




