---
title: "ReAnalysis Table"
author: "CT"
date: "Thursday, November 05, 2015"
output: html_document
note: Re analysis data compilation; Days, TT and Photop.
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)

```


```{r loadFile}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\ReAnalysis")
getwd()

#create file
df_Re <- read.table("ReAnalysisData.txt",header=TRUE)

head(df_Re)

summary(df_Re)

#change formats 

df_Re$SowingDate <-dmy(df_Re$SowingDate)
df_Re$StartFlowering <-dmy(df_Re$StartFlowering)
```

Graph Box Plot 

```{r GraphBoxPlot}

# Graph DAS and Location 

df_Re %>%
  filter(Location != "Canberra"& Location != "Lismore") %>%
  ggplot(aes(x=Country, y=DaysToFlower)) + 
  geom_boxplot(alpha =0.2) +
  geom_violin(alpha =0.2)+
  geom_jitter(aes(colour=Location), width=0.25)+
  labs(y="DAS",x="Country")



 df_Re %>%
   ggplot(aes(x=AuthorYear, y=TtFlowerAdjusted)) + 
    geom_boxplot() +
  geom_jitter(width=0.25) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))


#Graph PhotoPTarget and TT Flower per Author 

 df_Re %>%
  ggplot(aes(x=PhotopAtTtTarget, y=TtFlowerAdjusted)) + 
  geom_point(aes(colour=AuthorYear)) 
  facet_wrap (~AuthorYea,ncol=10, scales = "free")
  #+
  #labs(y="Percentage plants with first Trifoliate",x="Days after sowing") +
    # facet_wrap(~AuthorYear, scales = "free")
  

```
Graph Photperiod and TT flower per Location and cultivar 


```{rGraphFacetwrap}
head(df_Re)


# location 
df_Re %>%
  filter(Location =="Launceston" | Location =="Katanning") %>%
  ggplot(aes(x=PhotopAtTtTarget, y=TtFlowerAdjusted)) + 
  geom_line(aes(colour=Treatcultivar)) +
  geom_point(aes(colour=Treatcultivar)) +
  facet_grid(.~Country, scales = "free")

#analysis cultivar 

df_Re %>%
  filter(Treatcultivar =="Tallarook" | Treatcultivar =="MtBarker") %>%
  ggplot(aes(x=PhotopAtTtTarget, y=TtFlowerAdjusted)) + 
  geom_line(aes(colour=Location)) +
  geom_point(aes(colour=Location)) +
  facet_grid(Treatcultivar~Country, scales = "free")
  
  #labs(y="Percentage plants with first Trifoliate",x="Days after sowing") +
    # facet_wrap(~AuthorYear, scales = "free")

```




