---
title: "ReAnalysis Table"
author: "CT"
date: "Thursday, December  05, 2016"
output: html_document
note: Re analysis : include Pp analysis using selected datasets from Reanalysis4 (df_REa6)
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library (segmented)

```
 


```{r   loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover\\ReAnalysis")

getwd()

#get dataframe created in ReAnalysis4
df_1 <- read.table("df_Rea6.txt",header=TRUE)

#head(df_Data)

#summary(df_Rea6)

# Here used just to save unique values of indexes 

# xx <- unique(df_Rea6$indexLocCult)
# 
# write.csv(xx, "listOfExpCultUsedForPp.csv")

df_Gr <- read.table("CultivarGroup.txt",header=TRUE)

#now merge the two df 

df_Rea6 <- merge(df_1, df_Gr,by=c("indexLocCult"))

summary (df_Rea6)

```


```{r}
df_Rea6 %>%
  #filter(indexLocCult=="Launceston1987_Meteora")%>%
  ggplot(aes(x=month(SowingDate), y= Value, colour=Treatcultivar)) +
  geom_point(shape=21) +
 geom_smooth(se=FALSE)+
  #theme(legend.position="none")+
  facet_grid(Variable~., scales = "free")
```



Select two groups of cultivars : hight Pp sensitive response varies and low sensitive cultivar group (TT decreases at the end )

```{r, warning=FALSE}
#Check data filtering indexLocCult. See r2 generated below. 
df_Rea6 %>%
  #filter(indexLocCult=="Launceston1987_Meteora")%>%
  ggplot(aes(x=month(SowingDate), y= Value, colour=SensGroup)) +
  geom_point(shape=21) +
 #geom_smooth(se=FALSE)+
  #theme(legend.position="none")+
  facet_grid(Variable~., scales = "free")
```


```{r}

#Check data filtering indexLocCult. See r2 generated below. 
df_Rea6 %>%
  filter(Variable=="TTFloAdj")%>%
  ggplot(aes(x=Pp, y= Value, colour=SensGroup)) +
  geom_point(shape=21) +
 #geom_smooth(se=FALSE)+
  #theme(legend.position="none")+
  facet_grid(Variable~., scales = "free")


```






```{r, warning=FALSE}

#Check cvs 
df_Rea6 %>%
dplyr::filter(Treatcultivar=="Nungarin"|
         Treatcultivar=="SeatonPark"|
           Treatcultivar=="Trikkala"|
           Treatcultivar=="Dalkeith")%>%
  ggplot(aes(x=Pp, y= Value, colour=indexLocCult)) +
  geom_point(shape=21) +
 geom_smooth(se=FALSE)+
  #theme(legend.position="none")+
  facet_grid(Variable~SensGroup, scales = "free")



```




Create function for retrieving photoperiod as a function of TT after sowing


```{r}

df_weather <- read.table("df_CumTT.txt",header=TRUE)

df_weather <-df_weather %>%
  select(LocationYear,Date, Pp, SumTTday)

summary(df_weather)

```

```{r}


Pp_finder_func <- function(idx_loc,tt_target){
  
  #isolate the experiment and cultivar 
  df_temp_wea <- df_weather %>%
    filter(LocationYear == idx_loc)
  
 # tt_target <- tt_sow + tt_extra
  
  # lookup for Pp at new tt sum
  tryCatch(  
  Pp_target <- approx(df_temp_wea$SumTTday, 
  df_temp_wea$Pp, xout = tt_target, rule = 1)$y,
  error = function(e) 
  {
  Pp_target <- NA
  }
)
 
  return(Pp_target)
  
}
```

```{r}
#test
tt_target <- 2172.8526
#TTsum estimated to reach 1st trifoliate 

#test if function is working : example : 
Pp_finder_func("Katanning1990",tt_target)
```

Create the loop to identify each combination of indexLocCult - isolate and calculate stats for each Pp target. 

```{r}

#Flowering reference = Floref
floref <- 50

TTpercflo <- 2.6 # degree days from 5 to full (100) flowering 
#value calculated from DearEtAL1993_Reanalysis3 script


#loop

cvGroup <- unique(df_Rea6$SensGroup)
vc_temp <- vector()
vc_all <- vector()

for(i in 1:length(cvGroup)){
  
  for(t in seq(0,1500, by=100)){
   
   #print(t)
  #print(i)
 
  cvG <- cvGroup[i]
  
  #print(s) 
  
  df_s <- df_Rea6 %>%
    dplyr::filter(SensGroup == cvG) %>%
    filter(Variable=="TTFloAdj") %>%
    mutate(ttFlowZero=Value-(floref*TTpercflo)) %>% 
    mutate(z=TTSumSow + t) %>% #define multiple tt after sowing for which Pp needs to be retrieved 
    mutate(TT_target= ifelse (z > ttFlowZero,
                             ttFlowZero,
                             z)) %>%
    #mutate(z=TTSumSow + t) %>% #testing Pp even if Pp greater than experienced by crop
    rowwise() %>%
    mutate(Pp_target=Pp_finder_func(as.character(LocationYear),TT_target)) # functions gets a charater therefore format change
     
    #print(unique(df_s$indexLocCult))
    
    x <- as.numeric(df_s$Pp_target)
    y <- as.numeric(df_s$Value)
  
  # test alternative functions - all gave highest first R2 at ~ 600oCd - Not resolved
 #  polyM <- lm(formula = y ~ poly(x, 3)) # testing simple polinomial
 #  expM <- lm(log(y)~ x)
 #  print(t)
 #  print( summary(polyM)$r.squared*100)
 #  summary(polyM)
  # -------
  
  out.lm <-lm(Value~Pp_target,data=df_s)
  
  o <- segmented(out.lm,seg.Z=~Pp_target,psi=list(Pp_target=13),
                   control=seg.control(display=FALSE))
  
  # test plot FIXME: Does not display what we expected?
  print(t)
  plot(x,y, pch=16)
  plot(o, add=T, link=TRUE)
  
      
  
  # find stats
      s <- slope(o)$Pp[,1]    
      interc <- intercept(o)
    
      r2 <- round(summary.segmented(o)$adj.r.squared*100,digits=5)
      slope1 <- round(s[1], digits = 4)
      slope2 <- round(s[2], digits = 4)
      pVs1 <- summary.segmented(o)$coefficients[14]#pvalue slope1
      pVs2 <-summary.segmented(o)$coefficients[15]#pvalue slope2
      
      # find breaks
      b = o$psi[,2]
      
      vc_temp <- c(as.character(cvG),t, r2,slope1,slope2,pVs1,pVs2,b)
      vc_all <- rbind(vc_all,vc_temp)
      # show slopes and breakpoints
      #print(paste0(" slope: ",s, " break: ", b))
      
     # print(summary(o))
  
}  #this ends the loop of multiple thermal time
vc_temp <-NULL
 } #end loop high and low sensegroup of cultivars
  
 
 df_all <-data.frame(vc_all)
 colnames(df_all) <-c("CvGroup","TTjuv", "r2","slope1","slope2","pVs1","pVs2","b")
 
 # FIXME: The resulting model does not align with the best "visual" fit at 900oCd Tt juveline
 

```

```{r}
#graph it 

df_all %>%
   ggplot(aes(x=as.numeric(as.character(TTjuv)), 
              y=as.numeric(as.character(r2)), colour=CvGroup)) +
   geom_point() 
```


```{r , warning = FALSE}

# find highrest r2

#graph PPat 1000TTjuv 
df_opt <- df_all %>%
group_by(CvGroup) %>%
filter(r2==max(as.numeric(as.character(r2))))

#tt_extra_opt <- 700

ggg <- c("High","Low")

# for(gg in 1:length(ggg)) {
# for(tte in 1:length(tt_extra_opt)) {
  
   g <- df_Rea6 %>%
     rowwise() %>%
    #dplyr::filter(SensGroup == ggg[gg]) %>%
    filter(Variable == "TTFloAdj") %>%
     mutate(tt_extra_opt=as.numeric(ifelse(SensGroup=="High",1000,700)))%>%
     mutate(TT_target = TTSumSow + tt_extra_opt) %>% #define multiple thermal time after sowing for which photoperiod needs to be retrieved 
    
    mutate(Pp_target = Pp_finder_func(as.character(LocationYear),TT_target)) %>%
    
    ggplot(aes(x=Pp_target,y=Value)) +
    geom_point() + 
    # stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1) + 
     stat_smooth(method = "lm", formula = y ~ poly(x, 2), size = 1)+
     geom_abline(intercept = ifelse(df_Rea6$SensGroup=="High",1000,700), slope=0,linetype=2)+
     facet_wrap(~SensGroup)

   
   print(g)
  
# }
# 
# }

# loop acros multiple TT extras
# select best stats or simply store all (better I think) and test in next chunck

```



