---
title: "ReAnalysis Table"
author: "CT"
date: "Thursday, December  05, 2016"
output: html_document
note: Re analysis data and weather files : merge .
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)

```
 


```{r   loadFile}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover\\ReAnalysis")
getwd()


#get dataframe created in ReAnalysis1
df_Rea3 <- read.table("df_Rea3.txt",header=TRUE)


#head(df_Data)

summary(df_Rea3)

```

Use slope values (Rea3) to normalise TT flowering 

```{r}
#Flowering reference = Floref
floref <- 50

TTpercflo <- 2.6 # degree days from 5 to 100 flowering (value calculated from DearEtAL1993_Reanalysis3 script)

df_Rea4 <- df_Rea3 %>%
  mutate(TTFloAdj=((floref-PercentFlower)*TTpercflo )+TTtoFlower)

summary(df_Rea4)

  
```


```{r}
#graph TTtoFlower vs TTFloAdj
#Check TT 
df_Rea4  %>% 
ggplot(aes(x=TTtoFlower, y= TTFloAdj)) +
    geom_point(shape=21)+
  geom_abline(intercept = 0, slope = 1)

```

plot TTadj vs. sowing date

```{r , fig.height=5, fig.width=10}
df_Rea4  %>% 
  filter(Treatcultivar=="Woogenellup") %>%
ggplot(aes(x=month(SowingDate), y= TTFloAdj, colour=Treatcultivar)) +
    geom_point(shape=21) +
  scale_x_continuous(breaks = c(2,4,6,8,10,12))+
 # geom_smooth()+
  facet_grid(Country~.)


```

plot TTadjst vs. LocationYear

```{r, fig.height=5, fig.width=10}
df_Rea4  %>% 
  #filter(Treatcultivar=="Woogenellup") %>%
ggplot(aes(x=LocationYear, y= TTFloAdj, colour=Treatcultivar)) +
    geom_point(shape=21) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  facet_grid(Country~.)
```




Photoperiod at sowing 

```{r, fig.height=5, fig.width=10}

#Check TT 
df_Rea4  %>% 
ggplot(aes(x=Pp, y= TTFloAdj, colour=Treatcultivar)) +
    geom_point(shape=21) +
  facet_grid(Country~.)

```





