---
title: "ReanalysisTT"
author: "CT"
date: "27 December 2016"
output: html_document
---

```{r setup, include=FALSE, loadlibraires}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)

```



```{r readData}
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover\\ReAnalysis")
getwd()

#create file
df_We <- read.table("RawWeather.txt",header=TRUE)

#head(df_We)

summary(df_We)
```



```{r changeformat, echo=FALSE}

df_We$Date<-dmy(df_We$Date)

str(df_We)

```

## Graph it 

```{r, fig.height=10, fig.width=10}

df_We %>%
  tidyr::gather("Variable", "Value",Tx:Pp) %>%
  ggplot(aes(x=Date,y=Value))+
  geom_line(aes(colour=factor(Variable))) +
  facet_wrap(~LocationYear,scale="free") +
  scale_color_manual(values=c("#333333", "#9999CC", "#CC3300"))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 


```

## Define Tt cardinal temperatures

```{r}

#Create Thermal time cardinal temperatures 
tt_card <- data.frame(temp=c(0,20,30,50),TT=c(0,20,20,0))
tt_card %>%
  ggplot(aes(x=temp, y=TT))+
  geom_line()
  
#FIX ME include REF Thermal time 
```

```{r}

#Create and test interpolation function 

temp_ref  <- 25 # x-axes reference
temp <- tt_card$temp # x-axes
TT <- tt_card$TT # y-axes


int_func <- function(temp,TT,temp_ref){

  # if temp is too low or too high give extreme TT values
 if(temp_ref>temp[length(temp)]) {
   
   out <- TT[length(TT)] 
   # FIXME: approx functions seems to do that - need param
   
 } else if (temp_ref<temp[1]) {
   
   out <- TT[1]
   
 } else {
   
   # else interpolate
   
   tryCatch(  
   
  out <- approx(temp, TT, xout = temp_ref, 
         method="linear", 
         rule = 2)$y,
  error = function(e) 
  {
  out <- NA
  }
) 
  
} # end if check

  return(out)  
  
 }
  
int_func(temp,TT,temp_ref)


```

```{r}

#create REF 

TTfunc <- function(Tmin ,Tmax){         
 
  if (Tmin>Tmax){
   print("Tmin>Tmax")
   break
 } 
  
  TTav  <- 0
  TTsum <- 0
  
  for(n in 1:8){ 
    
    tn <- 0
    
    TT_tn <- 0
    
    tn <- ((0.931 +  0.114*n - 0.0703 * n^2
            + 0.0053 * n^3) * (Tmax-Tmin)) + 
      Tmin # 8-h temperature
    
    TT_tn <- int_func(tt_card$temp, tt_card$T,tn) 
    
    TTsum <- TT_tn + TTsum
    
    print(TT_tn)
    
    }
  TTav <- TTsum/8
  
  return(TTav)
  }

TTfunc(10,30)

```

```{r ReadCalcTt}

df_We_tt <- df_We %>%
  mutate(TTday=TTfunc(Tm,Tx))
```

