 ---
title: "ReanalysisTT"
author: "CT"
date: "27 December 2016"
output:
  word_document: default
  html_document: default
---

```{r setup, warning=FALSE}

library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(scales)

```



```{r readData}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\ReAnalysis")
getwd()

#create file
df_We <- read.table("RawWeather.txt",header=TRUE)

#head(df_We)

summary(df_We)
```

## Graph it 

```{r, fig.height=10, fig.width=10}

df_We %>%
  mutate(Date=dmy(df_We$Date)) %>%
  filter(LocationYear != "Mininera2005") %>%
  tidyr::gather("Variable", "Value",Tx:Pp) %>%
 #mutate(Month=format(as.Date(dmy(as.character(Date))),"%b")) %>%
  ggplot(aes(x=Date,y=Value))+
  geom_line(aes(colour=factor(Variable))) +
  facet_wrap(~LocationYear,scale="free") +
  labs(x=" Date", y=" degree Celsius/hours  ")+
  scale_color_manual(values=c("#333333", "#9999CC", "#CC3300"))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_x_date(labels = date_format("%b-%Y"))


```

## Define Tt cardinal temperatures

Considered an overall average the following references:
Tb: 0.0
Top range:18-25
Tmax: 40
REFS: MonksEtAl2009	,LonatiEtAl2009	,MootEtal2003, SilsburyetAl1984. 
							


```{r, fig.height=5, fig.width=10}

#Create Thermal time cardinal temperatures see REFs Moot et al 2000, Lonati, 2009, Monks 2009, Silsbury 1984 ! 

tt_card <- data.frame(temp=c(0,15,22,35),TT=c(0,15,15,0))
tt_card %>%
  ggplot(aes(x=temp, y=TT))+
  #labs(x="Temperature (degree Celsius)")+
  #labs(y="Thermal Time (oCd)") +
  geom_line()+
  theme_bw()+
  ylim(0,20)+
xlab(expression(Temperature~"("^"o"*"C)"))+
  ylab(expression(Thermal~Time~"("^"o"*"Cd)"))+
  theme(axis.text.x=element_text(angle = 0, hjust = 0, size= 14))+
  theme(axis.title.x=element_text(angle = 0, hjust = 0.5, size= 14))+
  theme(axis.text.y=element_text(angle = 0, hjust = 0, size= 14))+
  theme(axis.title.y=element_text(size= 14))
  
#
```

```{r}

#Create and test interpolation function - Test if works 

temp_ref  <- 25 # x-axes reference
temp <- tt_card$temp # x-axes
TT <- tt_card$TT # y-axes


int_func <- function(temp,TT,temp_ref){

  # if temp is too low or too high give extreme TT values
 if(temp_ref>temp[length(temp)]) {
   
   out <- TT[length(TT)] 
   # FIXME: approx functions seems to do that - need param
   
 } else if (temp_ref<temp[1]) {
   
   out <- TT[1]
   
 } else {
   
   # else interpolate
   
   tryCatch(  
   
  out <- approx(temp, TT, xout = temp_ref, 
         method="linear", 
         rule = 2)$y,
  error = function(e) 
  {
  out <- NA
  }
) 
  
} # end if check

  return(out)  
  
 }
  
int_func(temp,TT,temp_ref)

```

```{r}

#create REF Jones CA, Ritchie JT, Kiniry JR, Godwin DC (1986) Subroutine structure.In 'CERES-Maize: A simulation model of maize growth anddevelopment'. (Eds CA Jones, JR Kiniry) pp. 49-194. (Texas A&M University Press: Texas, USA

TTfunc <- function(Tmin ,Tmax){         
 
  if (Tmin>Tmax){
   print("Tmin>Tmax")
   break
 } 
  
  TTav  <- 0
  TTsum <- 0
  
  for(n in 1:8){ 
    
    tn <- 0
    
    TT_tn <- 0
    
    tn <- ((0.931 +  0.114*n - 0.0703 * n^2
            + 0.0053 * n^3) * (Tmax-Tmin)) + 
      Tmin # 8-h temperature
    
    TT_tn <- int_func(tt_card$temp, tt_card$T,tn) 
    
    TTsum <- TT_tn + TTsum
    
    print(TT_tn)
    
    }
  TTav <- TTsum/8
  
  return(TTav)
  }

TTfunc(10,30)

```

```{r ReadCalcTt}

df_We_tt <- df_We %>%
  mutate(TTday=TTfunc(Tm,Tx), TTday_s=(Tm+Tx)/2, diff=(TTday_s/TTday)*100)

```


```{r}
#Check TT  two methods : TTday_s = simple method (Tmean - Tbzero)
df_We_tt  %>% 
ggplot(aes(x=TTday_s, y= TTday)) +
    geom_point(shape=21,alpha=0.2)+
  geom_abline(intercept = 0, slope = 1)

```





```{r}

#change formats 

df_We_tt$Date <-dmy(df_We_tt$Date)


str(df_We_tt)

#Calculate accumulated Themal time 

df_CumTT <- df_We_tt %>%
group_by(LocationYear) %>%
arrange(Date) %>%
mutate(SumTTday = cumsum(TTday)) %>%
mutate(DayCount=Date-min(Date))

head(df_CumTT)
str(df_CumTT)

```

```{r, fig.height=10, fig.width=10}
#Graph Accumulated TT 

df_CumTT %>%
  ggplot(aes(x=DayCount,y=SumTTday))+
  geom_line(aes(colour=LocationYear, linetype=Country)) +
  #facet_wrap(~LocationYear,scale="free") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlim(0,300)+
  ylim(0,5000)

```




```{r}

write.table(df_CumTT, "df_CumTT.txt")

```

