---
title: "Germination Seeds different Temperatures  4Cultivar"
author: "CT"
date: " September  , 2015"
output: html_document
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)  
library(agricolae)
library(knitr)
library (lubridate)

```


```{r loadFile}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\SeedGermTemp")
getwd()

#create file
df_seed <- read.table("SeedGerm1.txt",header=TRUE)
head(df_seed)
# Jeito 1 de trocar formato (usando base R)
df_seed$Date <- dmy(df_seed$Date)

# jeito 2 de trocar formato (usando dplyr)
df_seed <- df_seed %>%
  mutate(Temp = as.factor(Temp), Block = as.factor(Block))%>%
#  mutate(PropSoft =round((Soft/SeedNumber)*100),2)
  mutate(PropGerm = round(CountedGerm/50*100,digits=2))

summary(df_seed) # explore values
str(df_seed) # check formats


```



```{r}
df_seed1 <-df_seed%>%
  group_by(Cultivar, Temp,DAS, HoursofTest)%>%
  dplyr::select(CumPercent) %>%
  summarise_all(funs(mean,sd))



```

```{r, fig.height=5, fig.width=10}
df_seed1%>%
ggplot(aes(x=HoursofTest, y=mean, colour=factor(Cultivar))) + 
  geom_point()+
  geom_line()+
  #labs(x="Hours",y="Cummulative Germination Percnet(%)")+
  #facet_grid(.~Temp)
  #facet_wrap(.~Temp, ncol=6)
facet_wrap(~Temp,ncol=6, scales = "free")+
  theme_bw()+
  scale_x_continuous(breaks = c(100,200,300))+
  ylim(0, 120)+
  #xlim(0, 400)+
  labs(y="Mean cumulative germination Percent",x="Hours of test")+ 
  geom_abline(intercept = 50, slope = 0)
```


build a graph black and white 


```{r, fig.height=5, fig.width=15}
#Here how to create the end error bar with max Sd 
# find size of bar per month
# find single position of x y to put the bar

#extraPos<- 1.10 # extra position for single error bar
extraPos<- 1.2 # extra position for single error bar
x_max<-max(df_seed1$DAS)
y_max<-max(df_seed1$mean)

# find largest standard error
sd_df <- df_seed1 %>% 
  group_by(Temp) %>%
  dplyr::select(sd)%>%
  summarise_all(max)%>%
  #summarise(max_sd = max(sd)) %>% 
  ungroup() %>%
  rowwise() %>%
  #rename variables
  mutate(DAS = x_max*extraPos, mean = y_max*extraPos,max_sd=sd )

summary(sd_df)

#divide sd/2 as number of replicates were 4 

df_seed1%>%
ggplot(aes(x=DAS, y=mean)) + 
  geom_point(aes(shape=Cultivar),size=4)+
  #scale_shape_manual(values = c(0,1,2,3,4))+
  scale_shape_manual(values = c(1,2,4,7))+
  geom_errorbar(data=sd_df, aes(ymin=mean-max_sd/2,
                    ymax=mean+max_sd/2), width=4)+
  facet_wrap(~Temp,ncol=6, scales = "free")+
  theme_bw()+
  #scale_x_continuous(breaks = c(5,10,15,20,30))+
  ylim(0, 180)+
  xlim(0, 25)+
  labs(y="Mean cumulative germination %",x="Days of test")+ 
  #theme(axis.title.x = element_text( size=24)) + scale_x_continuous(breaks = c(0:6))+
  theme(text=element_text(size=18 ))+
  theme(title=element_text(size=22, face="bold"))+
  theme(title=element_text(size=22,  face="bold"))+
   #remove grid lines 
     theme(
     #panel.border = element_rect(colour = "black"  , size = 2.0), 
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank(),
     axis.line = element_line(colour = "black"))+
  
  
  #geom_abline(intercept = 50, slope = 0)


ggsave("plot_CumulativeGerm.png", width=12, height=6, dpi=400)

```



graph it 



```{r, fig.height=5, fig.width=10 }

#Create a graph with days instead of hours of test 

#graph it
 df_seed1 %>%
  
ggplot(aes(x=DAS, y=mean, colour=Temp)) + # do percentage here
 
  geom_point(aes(shape= Temp), size=2.5)+
  scale_shape_manual(values = c(0,1,2,3,4,5,6,7,8,9,10,11))+
  geom_line()+
    #labs(x="Hours",y="Cummulative Germination Percent(%)")+
  #facet_grid(.~Temp)
  #facet_wrap(.~Temp, ncol=6)

facet_wrap(~Cultivar,ncol=2, scales = "free")+
  theme_bw(base_size=16)+
  #scale_x_continuous(breaks = c(1,200,300))+
  ylim(0, 100)+
  xlim(0, 18)+
  theme(axis.text.x=element_text(angle = +0, hjust = 0, size= 12))+
  theme(axis.text.y=element_text(angle = +0, hjust = 0, size= 12))+
  labs(y="Mean cumulative germination Percent (%)",x="Days of test")
 # geom_abline(intercept = 50, slope = 0)

 




```


```{r}
#Create a table with the folloing columns to use in analysis "Temp"  "Cultivar" "Block" "DAS" "PercGerm_cum" "Plot"

dfgerm <-df_seed %>%
  dplyr::select(Temp, Cultivar, Block, DAS, Plot, CumPercent, ActTemp)%>%
  mutate( PercGerm_cum = CumPercent)%>%
   dplyr::select(- CumPercent )


write.table(dfgerm, "df_SeedGermCum.txt")
```




