---
title: "Germination Seeds different Temperatures  4Cultivar"
author: "CT"
date: " September  , 2015"
output: 
  word_document: default
  pdf_document: default
  html_document: default
---

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)  
library(agricolae)
library(knitr)
library (lubridate)
library(survival)
library(growthmodels)

```


```{r loadFile}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\SeedGermTemp")
getwd()

#create file
df_seed <- read.table("dataToCurveFitGerm.txt",header=TRUE)
attach(df_seed)
head(df_seed)



```


```{r}



# jeito 2 de trocar formato (usando dplyr)
df_seed <- df_seed %>%
  mutate(Temp = as.factor(Temp), Block = as.factor(Block), PercentRelative=as.numeric(PercentRelative/100))%>%
  dplyr::select(Plot:PercentRelative)

str(df_seed) # check formats



```

Try data with just one plot to test function 

```{r}
df_Plot65<-df_seed %>%
  filter(Plot=="65")%>%
  dplyr:: select(DAS,PercentRelative)


```

Use simple method to fit a curve non linear model 

```{r}


plot(df_Plot65)




```













Now use this mini set to fit a curve 


```{r}

growth <-df_Plot65 %>%
   gompertz(0:16, 16, 0.5)

summary(growth)

plot(growth)




```




Use same procedure for survival analysis 



```{r}

# define variables 

time <-DAS
event <- PercentRelative/100
group <- Cultivar


```

Descriptive stats
```{r, fig.height=5, fig.width=10}

#DEscriptive statitistics 
summary(time)
summary(event)
summary(Cultivar)


```


```{r}
plot (time, event, pch=15)


```

Perform the logistic regression 

```{r}


Eq.glm <- glm(event~time,data=df_seed, family=binomial)
summary(Eq.glm)

```




Kaplan Meyer non parametric analysis 




```{r}
kmsurvival <- survfit(Surv(time,event) ~1)
summary(kmsurvival)
plot(kmsurvival, xlab="Time", ylab="Survival Probability")


```



Try weibull equations 
```{r}

weibull <- survreg(Surv(time,event), dist = "weibull")
summary(weibull)


```


```{r, fig.height=5, fig.width=15}
#Here how to create the end error bar with max Sd 
# find size of bar per month
# find single position of x y to put the bar

#extraPos<- 1.10 # extra position for single error bar
extraPos<- 1.2 # extra position for single error bar
x_max<-max(df_seed1$DAS)
y_max<-max(df_seed1$mean)

# find largest standard error
sd_df <- df_seed1 %>% 
  group_by(Temp) %>%
  summarise(max_sd = max(sd)) %>% 
  ungroup() %>%
  rowwise() %>%
  mutate(DAS = x_max*extraPos, mean = y_max*extraPos)

summary(sd_df)

#divide sd/2 as number of replicates were 4 

df_seed1%>%
ggplot(aes(x=DAS, y=mean)) + 
  geom_point(aes(shape=Cultivar),size=4)+
  #scale_shape_manual(values = c(0,1,2,3,4))+
  scale_shape_manual(values = c(1,2,4,7))+
  geom_errorbar(data=sd_df, aes(ymin=mean-max_sd/2,
                    ymax=mean+max_sd/2), width=4)+
  facet_wrap(~Temp,ncol=6, scales = "free")+
  theme_bw()+
  #scale_x_continuous(breaks = c(5,10,15,20,30))+
  ylim(0, 180)+
  xlim(0, 25)+
  labs(y="Mean cumulative germination %",x="Days of test")+ 
  geom_abline(intercept = 50, slope = 0)


ggsave("plot_CumulativeGerm.png", width=12, height=6, dpi=400)

```



graph it 



```{r, fig.height=5, fig.width=10 }

#Create a graph with days instead of hours of test 

#graph it
 df_seed1 %>%
  
ggplot(aes(x=DAS, y=mean, colour=Temp)) + # do percentage here
 
  geom_point(aes(shape= Temp), size=2.5)+
  scale_shape_manual(values = c(0,1,2,3,4,5,6,7,8,9,10,11))+
  geom_line()+
    #labs(x="Hours",y="Cummulative Germination Percent(%)")+
  #facet_grid(.~Temp)
  #facet_wrap(.~Temp, ncol=6)

facet_wrap(~Cultivar,ncol=2, scales = "free")+
  theme_bw(base_size=16)+
  #scale_x_continuous(breaks = c(1,200,300))+
  ylim(0, 100)+
  xlim(0, 18)+
  theme(axis.text.x=element_text(angle = +0, hjust = 0, size= 12))+
  theme(axis.text.y=element_text(angle = +0, hjust = 0, size= 12))+
  labs(y="Mean cumulative germination Percent (%)",x="Days of test")
 # geom_abline(intercept = 50, slope = 0)

 




```


```{r}
#Create a table with the folloing columns to use in analysis "Temp" "Cultivar" "Block" "DAS" "PercGerm_cum" "Plot"

dfgerm <-df_seed %>%
  dplyr::select(Temp, Cultivar, Block, DAS, Plot, CumPercent )%>%
  mutate( PercGerm_cum = CumPercent)%>%
   dplyr::select(- CumPercent )


write.table(dfgerm, "df_SeedGermCum.txt")
```




