---
title: "R Notebook"
output: html_notebook
---


```{r loadLibraries}

library(tidyr)
library (dplyr)
library (ggplot2)  
library(agricolae)
library(knitr)
library (lubridate)

```



```{r   loadFile}
# Get dataframe from previous script (written table )
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\SeedGermTemp")
getwd()


```

```{r}
info <- read.table("CardinalTemps.txt" , header=TRUE)
summary(info)
```

```{r, fig.width=12}

info_work <- info %>%
  mutate(Tb2=Tb, Topt2=Topt,Tmax2=Tmax) %>%
  na.omit() %>%
  gather(VarName,VarValue,Tb:Tmax) %>%
  mutate(VarName=factor(VarName, levels=c("Tb","Topt","Tmax")))


b <-info_work %>%
  group_by(VarName) %>%
  summarise(bx=max(VarValue), bn =min(VarValue)) %>%
  gather("VarType","VarValue",bx:bn) %>%
  spread(VarName,VarValue) %>%
  ungroup()


info_work %>%
ggplot(aes(x=reorder(Cultivar,Tb2),y=VarValue)) +
 geom_point(size=6,alpha=0.5, aes(shape=VarName, colour=VarName)) +
  #geom_point(size=6,alpha=0.5, aes(shape=VarName, colour="black")) +
  #geom_point(colour= "black", alpha=0.2) +
  #geom_point(size=6,alpha=0.5, aes(shape=VarName)) +
 geom_abline(intercept = b$Tb, slope = 0, linetype=2, colour="grey") +
 geom_abline(intercept = b$Topt, slope = 0, linetype=2, colour='darkgrey') +
 geom_abline(intercept = b$Tmax, slope = 0, linetype=2, colour='black') +
  ylab(expression(Temperature~"("^"o"*"C)")) +
  xlab("Cultivar") +
  theme_bw()+
  coord_flip() + theme(legend.title=element_blank())+
  
  #remove grid lines 
     theme(
     panel.border = element_rect(colour = "black"  , size = 2.0), 
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank(),
     
     axis.line = element_line(colour = "black", size= 1))+

#make Cultivars  white  
   theme(strip.background = element_rect(colour = "black", fill = "white",size=2))+
  
  #label sizes 
theme(text = element_text(size = 26))
  

ggsave("plot_CardinalTempClovers.png", width=12, height=6, dpi=400)

```
