---
title: "Germination Seeds different Temperatures  4Cultivar"
author: "CT"
date: " September  2017"
output: 
  word_document: default
  pdf_document: default
  html_document: default
---
# this script calculates the TT based on Tb =0 for the 4 cvs 

```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)  
library(agricolae)
library(knitr)
library (lubridate)

```


```{r loadFile}
setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\SeedGermTemp")
getwd()

#create file Use here df_RAteGErm2 as it has the zeros to include in graphics 
df_seed <- read.table("df_RateGerm.txt",header=TRUE)
str(df_seed)
# change format with  base R)
#df_seed$Date <- dmy(df_seed$Date)

# jeito 2 de trocar formato (usando dplyr)
df_seed <- df_seed %>%
  mutate(Temp = as.numeric(Temp), 
         Block = as.factor(Block),
         Rate= as.numeric(Rate))


summary(df_seed) # explore values
str(df_seed) # check formats
```

Need to fix here ...Replace the NA's per zero values to graphic it  

```{r}
dfTT <-df_seed %>%
  dplyr:: select(-Rate,-PercentRelative)%>%
 # subset(DAS50E>0.7 )%>%
  subset(Temp>2.5 & Temp<25)%>%
  mutate(TT=(Temp*DAS50E))
  
dfTT2 <- dfTT %>%
  group_by( Cultivar) %>%
  dplyr::select(TT) %>%
  summarise_all(funs(mean,sd))


```



Graph DAS 50 vs temperature 


```{r, fig.height=5, fig.width=10}
#check format
#str(dMax)

# #graph it here error bars already represent the SE (std/sqrtn = 4)
a <- dfTT %>%
#   #ungroup()%>%
#   #mutate(Temp=as.numeric(Temp))%>%
group_by( Cultivar) %>%
  dplyr::select(TT)%>%
  summarise_all(funs(mean,sd)) 
  
# define position of bar and errorbar
dodge_x <- position_dodge(width = 0.9)
  # here sd/4 correspond to standard error 
  a %>%
  ggplot(aes(x=Cultivar, y=(mean))) +
  geom_bar(stat="identity",position = dodge_x) +
  geom_errorbar(aes(ymin=mean-sd/4,
                    ymax=mean+sd/4),
                width=0.25, size=0.3,position=dodge_x)   +
  theme_grey(base_size = 16) +
    theme_bw()+
   theme(text = element_text(size=16))+
  ylab(expression(Thermal~time ~"("^"o"*"Cd)"))+
  theme(axis.text.x=element_text(angle = +0, hjust = 0, size= 16))+
  theme(axis.text.y=element_text(angle = +0, hjust = 0, size= 16))
  
   
  

```

Get the means/stats  for  cultivar 
Vaariable : TT

```{r}
  #Prepare data frame for ANOVA
df_s<- dfTT
  
#-------------------------------------------------
# anova 
file <- df_s

file.subset <- file 

head(file.subset)
summary(file.subset)

```

```{r}

#ANOVA
my.anova <- aov(TT~ Cultivar + Block, data = file.subset)
#my.anova <- aov(TSW ~ Cultivar*Depth + Block, data = file.subset)
summary(my.anova)
```

```{r}

#(LSD.test(my.anova, c( "Cultivar"), alpha= 0.05, p.adj="none"))

(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none"))
#Note LSD interaction from Genstat was calculated as 0.7029 



#(LSD.test(my.anova, c( "Temp"), alpha= 0.05, p.adj="none"))

```



```{r}

(LSD.test(my.anova, c( "Temp"), alpha= 0.05, p.adj="none"))
```







 

