---
title: "Emergence seedlings I2"
author: "CT"
date: "02.10.2017"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

Purpose:

-this script does the  ANOVA for days to 50% emergence 




```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(mosaic)
library(lattice)
```


```{r loadFile}
#setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\EmergenceIv2")
setwd("C:\\GitHubRepos\\SubcloverPhD\\Subclover\\EmergenceIv2")

getwd()

#create file
df_emerg <- read.table("df_tt_50p_emerg.txt",header=TRUE)

str(df_emerg)


```


```{r}
# define factors 
df_emerg$Plot <- as.factor(df_emerg$Plot)
df_emerg$Block <- as.factor(df_emerg$Block)

 # df_emerg <- df_emerg %>%
 #  mutate(SowingDate = dmy(SowingDate), 
 #         ReadingDate = dmy(ReadingDate))
      

```
Here only change the df name and removed unwanted columns 


```{r ANOVAMaxPlantPop}

#compare max plant population among Sowing dates and cultivars

df_emerg_perc3 <- df_emerg%>%
  dplyr::select(SowTreat,Cultivar,Block,Plot,DAS50E)

```

Then select only woogenellup 


```{r}

dfW <- df_emerg_perc3 %>%
filter(Cultivar=="Woogenellup")%>%
filter (SowTreat== "S2"| SowTreat== "S3"|SowTreat== "S4"|SowTreat== "S6")
  

```




```{r}

  
```



Run ANOVA pure numbers for Woogenellup in 4 sowig dates 

```{r}
#data transf
file <- dfW
#this is to analyse DAS50E  
#file$transf_no <- 1*(dfW$DAS50E)


head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ SowTreat + Block, 
                data = file.subset)

summary(my.anova)



```

```{r}
#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("SowTreat"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))
```





then to run statistic tests select each sowing date individually

Stats for S2
 
```{r}

df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S2") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$DAS50E)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)

#TukeyHSD(my.anova)

```


```{r}

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))
```

Stats for S3

```{r}
df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S3") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)


```


```{r}
#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))
```

Stats for S4

```{r}
df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S4") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)

#TukeyHSD(my.anova)




```


```{r}
#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))
```


Stats for S5

```{r}

df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S5") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)

#TukeyHSD(my.anova)


```

```{r}
#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))
```

Stats for S6

```{r}
df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S6") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)


```

```{r}
#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))
```


Stats for S7 

```{r}

df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S7") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)



```


```{r}
#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))
```
Stats for S8

```{r}
df_emerg_S1 <-df_emerg_perc3 %>%
filter(SowTreat=="S8") 
summary (df_emerg_S1)  

#data transf
file <- df_emerg_S1
file$transf_no <- 1*(df_emerg_S1$FinalPop)
head(file)

#-------------------------------------------------
# ANOVA 
file.subset <- file 

head(file.subset, 50)
summary(file.subset)
my.anova <- aov(transf_no ~ Cultivar + Block, 
                data = file.subset)

summary(my.anova)


```

```{r}
#TukeyHSD(my.anova)

#Means separation 
(LSD.test(my.anova, c("Cultivar"), alpha= 0.05, p.adj="none") )
#(LSD.test(my.anova, "Cultivar"))
```

End of this script.
