---
title: "cumulative Emergence seedlings I2 Graph "
author: "CT"
date: "Thursday, December 31, 2015"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

Purpose:

-Graph the mean cumulative percentage of emergence 



```{r loadLibraries}
library(tidyr)
library (dplyr)
library (ggplot2)
library(agricolae)
library(knitr)
library (lubridate)
library(mosaic)
library(lattice)
```


```{r loadFile}
#setwd("C:\\GitHubRepos\\SubCloverPhD\\SubClover\\EmergenceIv2")
setwd("C:\\GitHubRepos\\SubcloverPhD\\Subclover\\EmergenceIv2")
getwd()

#create file
df_emerg <- read.table("Mean_CumulativeEmergence.txt",header=TRUE)



# define factors for the ones that "look like" values
#df_emerg$Plot <- as.factor(df_emerg$Plot)
#df_emerg$Block <- as.factor(df_emerg$Block)

# df_emerg <- df_emerg %>%
  #mutate(SowingDate = dmy(SowingDate), 
         # ReadingDate = dmy(ReadingDate),
         # PlantPop = (Sub1+Sub2+Sub3)/3/0.01)

str(df_emerg)
head(df_emerg)
tail(df_emerg)


#df_emerg %>% filter(Plot ==1) %>% summary()

df_seed1 <-df_emerg%>%
  mutate(SowTreat= factor(SowTreat, levels=c("S1", "S2", "S3", "S4", "S5", "S6","S7", "S8"),
                           labels=c("June", "July", "September", "November", "December", "February","March", "May")))

```


```{r, fig.height=15, fig.width=15}

str(df_seed1)

#extraPos<- 1.10 # extra position for single error bar
extraPos<- 1.1 # extra position for single error bar
x_max<-max(df_seed1$DAS)
y_max<-max(df_seed1$mean)

# find largest standard error
sd_df2 <- df_seed1 %>% 
  ungroup() %>%
  dplyr::select(DAS, SowTreat, mean, sd) %>%
  # dplyr::select(DAS, Cultivar, mean, sd) %>%
  group_by(SowTreat) %>%
 # group_by(Cultivar) %>%
 summarise_all(list(max)) %>%
#  mutate(max_sd = max(sd), max_mean=max(mean)) %>% 
  ungroup() %>%
  rowwise() %>%
  #rename variables
  mutate(DAS = DAS*extraPos, mean = mean*extraPos,max_sd=sd )

summary(sd_df2)

 

df_seed1%>%
ggplot(aes(x=DAS, y=mean)) + 
  geom_point(aes(shape= Cultivar, colour=Cultivar), size=3)+
 # geom_point(aes(shape= SowTreat, colour=SowTreat), size=3)+
  scale_shape_manual(values = c(0,1,2,3,4,5,6,7,8,9,10,11))+
  geom_line(aes(linetype=Cultivar))+
 #  geom_line(aes(linetype=SowTreat))+
  #geom_point(aes(shape=Temp),size=4)+
  #scale_shape_manu(al(values = c(0,1,2,3,4))+
   #scale_shape_manual(values = c(0,1,2,3,4,5,6,7,8,9,10)) +
  #scale_shape_manual(values = c(1,2,4,7))+
  #geom_line()+
  geom_errorbar(data=sd_df2, aes(ymin=mean-max_sd/1.73,
                    ymax=mean+max_sd/1.73), size=1.5)+
 # facet_wrap(~Cultivar,ncol=2, scales = "free")+
  facet_wrap(~SowTreat,ncol=2,scale="free")+
  theme_bw()+
  #scale_x_continuous(breaks = c(5,10,15,20,30))+
  #ylim(0, 145)+
  ##scale_y_continuous(breaks = c(0,500,1000,1500,2000,2500))+
  #xlim(0, 60)+
 xlab(expression(Days))+ 
  ylab(expression(Plant~population~"(seedlings/m"^"2"*")"))+
  #theme(axis.title.x = element_text( size=24)) + scale_x_continuous(breaks = c(0:6))+
  #theme(text=element_text(size=22 ))+
  theme(axis.title.x=element_text(angle = 0, hjust = 0.5,size = 22,face="bold"))+
  theme(axis.title.y=element_text(angle = 90, hjust = 0.5,size = 22,face="bold"))+
  #theme(title=element_text(size=22, face="bold"))+
  #theme(title=element_text(size=22,  face="bold"))+
   #remove grid lines 
     theme(
     panel.border = element_rect(colour = "black"  , size = 2.0), 
     panel.grid.major = element_blank(),
     panel.grid.minor = element_blank(),
     
     axis.line = element_line(colour = "black", size= 1))+
   ##thicks in axis
  theme(axis.ticks.length=unit(.3, "cm"))+

#make Cultivars  white  
   theme(strip.background = element_rect(colour = "black", fill = "white",size=2))+
  
  #label sizes 
theme(text = element_text(size = 26))
  
  #geom_abline(intercept = 50, slope = 0)


ggsave("plot_1_Emerg_CumulativePlantPopVsDAS.tiff", width=14, height=18, dpi=600)



```

End of this script 
