---
title: "Emergence seedlings I2 graphs with Mean Soil Temp"
author: "CT"
date: "10 May, 2016"
output: html_document
---

This script does this:
-get dataframe produced in Calc4EmergSoilT (df3; df_MeanSoilTemp50Emerg.txt)
-graph y=Days to 50% emergence ; x= mean soil Temp
-graph y= 1/days to 50% emergence ; x= mean soil Temp



```{r loadLibraries, warning=FALSE}
library(tidyr)
library(dplyr)
library(ggplot2)
library(agricolae)
library(knitr)
library(lubridate)
library(mosaic)
library(lattice)
library (gridExtra)
```


```{r loadFile}
# Get dataframe from previous script (written table )
setwd("C:\\Users\\EdCarmen\\Documents\\CarmenProjects2016\\GitSubclover\\EmergenceIv2")
getwd()

#create file
df_G <- read.table("df_MeanSoilTemp50Emerg.txt",header=TRUE)


df_G$Date50E <- ymd(df_G$Date50E)
df_G$SowingDate <- ymd(df_G$SowingDate )
df_G$Cultivar <- as.factor(df_G$Cultivar)
df_G$Plot <- as.factor(df_G$Plot)

summary(df_G)

# this is to "clean previous dfs : df_emerg4 <- NULL

```

Include 1/DAS50E 


```{r}

df_H <- df_G %>%
  mutate(InvDAS50E= 1/ DAS50E)

```


```{r, fig.height=5, fig.width=10, echo = FALSE}

#graph overall data 

#metFile <- data.table(metFile)

fontSize <- 12.0

#DAS50E
#g1 <- df_H %>%
  #filter(year %in% 1960:2000) %>%
  #group_by(day) %>%
 # summarise_each(funs(mean)) %>%
  g1 <- df_H %>%
  ggplot(aes(x=meanTemp_Em, y=DAS50E,shape=Cultivar))  +
  geom_point(colour= "darkblue", alpha=0.2) +
  geom_smooth()+
  #stat_smooth(level = 0.9, size = 1, colour="white") + 
  theme_bw() +
 xlab("Mean Soil Temp (oC)") + 
  ylab("Days to 50% emergence  (days)") +
  theme(text = element_text(size=10))

# 1/DAS50E
  g2 <- df_H %>%
  ggplot(aes(x=meanTemp_Em, y=InvDAS50E, shape=Cultivar))  +
  geom_point(colour= "red", alpha=0.2) +
  geom_smooth()+
  #stat_smooth(level = 0.9, size = 1, colour="white") + 
  theme_bw() +
  xlab("Mean Soil Temp (oC)") + 
  ylab("1/ Days to 50% emergence  (days)") +
  theme(text = element_text(size=10))

  
  grid.arrange(g1, g2)
# 

# 

```


ow do this for each cultivar separately 

```{r}



```



